---
editor: 
  markdown: 
    wrap: 72
---

# Ecotopenbeschrijving aquatisch {#sec-Aquatisch}

## Aquatisch \> getijdewateren {#sec-getijdewateren}

### Aquatisch \> zoete getijdewateren {#sec-zoete-getijdewateren}

De belangrijkste rijkswateren binnen het type zoete getijdenwateren zijn
de huidige en voormalige zoetwatergetijdengebieden en rivieren waar een
getijverschil van tenminste 30 centimeter aanwezig is. Voorbeelden
hiervan zijn de Biesbosch, Nieuwe Merwede, Amer, Oude Maas, Spui,
Dordtsche Kil, Noord, Beneden Merwede en Lek. Onderstaande tabel geeft
de 8 aquatische ecotopen en bijbehorende eco-elementen binnen deze
wateren.

TABEL PAG 38

##### Aquatisch \> getijdewateren \> Zeer diep, zoet getijdenwater {#sec-Zeer-diep-zoet-getijdenwater}

##### Aquatisch \> getijdewateren \> Diep, zoet getijdenwater {#sec-Diep-zoet-getijdenwater}

De ecotoopklasse zeer diep getijdenwater omvat de diepe geulen en kreken
die onder invloed staan van het getij en de rivier en die bij gemiddeld
laag water (GLW) dieper zijn dan 10 meter. De mechanische dynamiek is
zeer sterk, zodat transport van zand kan optreden. In de ecotoopklasse
diep getijdenwater (3 tot 10 meter) speelt dit ook nog, waardoor banken
en geulen kunnen ontstaan en weer verdwijnen. In een gedempt getijden-
systeem als het Haringvliet is de dynamiek sterk tot matig waardoor zand
maar ook slib tot bezinking kunnen komen. De opsplitsing naar bedding-
substraat (zand en slib) en harde substraten is ecologisch relevant voor
met name de macrofauna. Hard substraat bestaat uit glooiingen en
bestortingen van kribben, strekdammen en harde oevers.

##### Aquatisch \> getijdewateren \> Matig diep, zoet getijdenwater {#sec-Matig-diep-zoet-getijdenwater}

##### Aquatisch \> getijdewateren \> Ondiep, zoet getijdenwater {#sec-Ondiep-zoet-getijdenwater}

De ecotoopklassen matig diep en ondiep getijdenwater omvatten alle
(voor)oeverzones van geulen en ondiepe kreken met een diepte minder dan
3, respectievelijk 1 meter ten opzichte van gemiddeld laagwater (GLW)
die (nagenoeg) permanent watervoerend zijn en onder invloed staan van de
getijdenwerking en de rivier. De waterdiepte is het meest onderscheidend
ten opzichte van de andere ecotopen. De mechanische dynamiek in de
zandige geulen is relatief minder sterk dan in de diepere
getijdenwateren. Desondanks vindt er zand- en slibtransport plaats.

##### Aquatisch \> getijdewateren \> Eenzijdig aangetakte zoete getijdenkreek {#sec-Eenzijdig-aangetakte-zoete-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig diep aangetakte zoete getijdenkreek {#sec-Eenzijdig-diep-aangetakte-zoete-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig matig diep aangetakte zoete getijdenkreek {#sec-Eenzijdig-matig-diep-aangetakte-zoete-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig ondiep aangetakte zoete getijdenkreek {#sec-Eenzijdig-ondiep-aangetakte-zoete-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig zeer diep aangetakte zoete getijdenkreek {#sec-Eenzijdig-zeer-diep-aangetakte-zoete-getijdenkreek}

Naast de hoofdwateren zijn eenzijdig aangetakte getijdenkreken onder-
scheiden. Doordat ze niet tweezijdig open zijn, stromen ze niet mee met
het hoofd water en is de dynamiek geringer. Gei'soleerd liggende
begeleidende wateren komen sterk overeen met die onderscheiden bij
rivieren. Voor de indeling kan daarom worden uitgegaan van de ecotopen
beschreven in paragraaf [Rivierbegeleidende wateren]{.underline}. Omdat
deze wateren hier zeer sporadisch voorkomen, zijn ze verder niet
uitgewerkt of ecologisch beschreven.

Als eco-elementen zijn onderscheiden: bedekking met driehoeksmosselen,
waterplanten en helofyten. In ondiep water worden geen hoge dichtheden
aan driehoeksmosselen aangetroffen. In diep water is onvoldoende licht
voor een hoge dichtheid aan waterplanten. Op hard substraat in matig
diep en ondiep water en in kreken komen vermoedelijk ook eco-elementen
met waterplanten en mogelijk ook driehoeksmosselen voor.

> Omdat hier bij de ecologische beschrijving van hoofdstuk 5 verder geen
> invulling aan kon worden gegeven, zijn deze hier echter niet
> onderscheiden. Omdat de soorten- samenstelling zeer divers is, is
> binnen het eco-element waterplanten voor- alsnog geen onderverdeling
> gemaakt naar type waterplanten.

### Aquatisch \> zwak brakke en brakke getijdewateren {#sec-zwak-brakke-getijdewateren}

Zwak brakke en brakke getijdenwateren zijn op dezelfde wijze ingedeeld
in ecotopen als de zoete getijdenwateren. Ten aanzien van de
eco-elementen en de ecologische beschrijving en de benoeming van de
soorten behorend bij een referentietoestand (hoofdstuk 5) zijn er
duidelijke verschillen, met name als gevolg van de verschillende
zoutranges. Tot de (zwak) brakke getijdenwateren worden die rijkswateren
gerekend waar de invloed van de zee nog merkbaar is of op relatief korte
termijn weer verwacht mag worden. Voorbeelden binnen de rijkswateren
zijn: Nieuwe Maas, Hollandsche IJssel, Haringvliet en Hollandsch Diep.
In principe geldt de indeling ook voor de wateren Eems-Dollard,
Westerschelde en Nieuwe Waterweg. Er kon echter bij de opzet en
uitwerking van de ecotopen slechts in zeer geringe mate gebruik gemaakt
worden van kennis afgeleid uit deze watersystemen. Onderstaande tabel
geeft de 8 aquatische ecotopen binnen de zwak brakke en de brakke
getijdenwateren. Eco-elementen zijn onderscheiden op basis van ruime
aanwezigheid van benthos (inclusief schelpdieren), waterplanten (vooral
macrowieren) en helofyten.

##### Aquatisch \> getijdewateren \> Zeer diep, brak getijdenwater {#sec-Zeer-diep-brak-getijdenwater}

##### Aquatisch \> getijdewateren \> Diep, zwak brak getijdenwater {#sec-Diep-zwak-brak-getijdenwater}

Zeer diep en diep, (zwak) brak getijdenwater omvatten de brakke wateren
(geulen en diepe kreken) die onder invloed staan van het getij en de
rivier en die bij gemiddeld laag water (GLW) dieper zijn dan
respectievelijk 10 en 3 meter. Indien de menging groot is en er geen
sprake is van een zouttong, kunnen wateren dieper dan 10 meter toch aan
diep water toegekend wor- den. Bij deze klassen horen ook aan de wateren
grenzende harde oevers, kaden, bestortingen en pontons (hard substraat).
Verder kan hard substraat bestaan uit geconsolideerd veen of klei. De
mechanische dynamiek is zeer sterk tot matig. In zeer sterk dynamische
geulen kan transport van zand en schelpen optreden, waardoor banken en
geulen kunnen ontstaan en weer verdwijnen. Drijvende pontons in het
havengebied ondervinden slechts een geringe morfodynamiek. Het
zoutgehalte is afhankelijk van de diepte en de locatie in het estuarium.
In diep water is onvoldoende licht aanwezig voor een hoge dichtheid aan
waterplanten.

##### Aquatisch \> getijdewateren \> Matig diep, brak getijdenwater {#sec-Matig-diep-brak-getijdenwater}

##### Aquatisch \> getijdewateren \> Ondiep, brak getijdenwater {#sec-Ondiep-brak-getijdenwater}

De ecotoopklassen matig diep en ondiep, (zwak) brak getijdenwater
omvatten alle (zwak) brakke (voor)oeverzones van geulen en ondiepe
kreken met een diepte minder dan respectievelijk 3 en 1 meter ten
opzichte van gemiddeld laagwater (GLW) die (nagenoeg) permanent
watervoerend zijn en onder invloed staan van de getijdenwerking en de
rivier. Tevens behoren tot dit ecotoop de aan deze wateren grenzende
harde oevers, kaden, bestortingen en pontons (hard substraat). Verder
kan hard substraat bestaan uit geconsolideerd veen of klei. De
waterdiepte is het meest onderscheidend ten opzichte van de andere
ecotopen. De mechanische dynamiek in de zandige geulen is relatief
minder sterk dan in de diepe getijdenwateren. Desondanks vindt er zand-
en slibtransport plaats.

Als eco-elementen zijn onderscheiden: benthos, waterplanten en
helofyten. Omdat de samenstelling van de soorten zeer divers is, zijn de
eco-elementen benthos en waterplanten vooralsnog niet onderverdeeld naar
soort(groep). Op hard substraat in matig diep en ondiep water en in
kreken komen ver- moedelijk ook eco-elementen met waterplanten en
mogelijk ook driehoeks- mosselen voor. Omdat hier bij de ecologische
beschrijving van hoofdstuk 5 verder geen invulling aan kon worden
gegeven, zijn deze hier echter niet onderscheiden. Om dezelfde reden is
in hoofdstuk 5 bij de zwak brakke getijdenwateren geen invulling gegeven
aan het eco-element benthos bij diep en matig diep, zand/slib en ook
niet aan de eco-elementen benthos en waterplanten bij ondiep, zand/slib.

#### Aquatisch \> getijdewateren \> Eenzijdig aangetakte getijdenkreek {#sec-Eenzijdig-aangetakte-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig aangetakte, brakke getijdenkreek {#sec-Eenzijdig-aangetakte-brakke-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig aangetakte, zwak brakke getijdenkreek {#sec-Eenzijdig-aangetakte-zwak-brakke-getijdenkreek}

#### Aquatisch \> getijdewateren \> Eenzijdig ondiep aangetakte zwak brakke getijdenkreek {#sec-Eenzijdig-ondiep-aangetakte-zwak-brakke-getijdenkreek}

#### 

#### Aquatisch \> getijdewateren \> Aangetakte plas {#sec-Aangetakte-plas}

#### Aquatisch \> getijdewateren \> Brak aangetakte plas {#sec-Brak-aangetakte-plas}

#### Aquatisch \> getijdewateren \> Brak getijdenwater {#sec-Brak-getijdenwater}

#### Aquatisch \> getijdewateren \> Brak water achter vooroever {#sec-Brak-water-achter-vooroever}

#### Aquatisch \> getijdewateren \> Diep, brak getijdenwater {#sec-Diep-brak-getijdenwater}

#### Aquatisch \> getijdewateren \> Haven {#sec-Haven}

#### Aquatisch \> getijdewateren \> Matig diep {#sec-Matig-diep}

#### Aquatisch \> getijdewateren \> Matig diep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Matig-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Matig diep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Matig-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### 

#### Aquatisch \> getijdewateren \> Matig diep, brakke getijdenkreek {#sec-Matig-diep-brakke-getijdenkreek}

#### Aquatisch \> getijdewateren \> Matig diep, zwak brak getijdenwater {#sec-Matig-diep-zwak-brak-getijdenwater}

#### Aquatisch \> getijdewateren \> Matig tot gering dynamisch water (achter vooroever) {#sec-Matig-tot-gering-dynamisch-water-achter-vooroever-}

#### Aquatisch \> getijdewateren \> Matige diepe nevengeul {#sec-Matige-diepe-nevengeul}

#### Aquatisch \> getijdewateren \> Ondiep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Ondiep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Ondiep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Ondiep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Ondiep, zwak brak getijdenwater {#sec-Ondiep-zwak-brak-getijdenwater}

#### Aquatisch \> getijdewateren \> Ondiepe nevengeul {#sec-Ondiepe-nevengeul}

#### Aquatisch \> getijdewateren \> Rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Rivierbegeleidend water (\</\> 20 d/j overstroomd) {#sec-Rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Zeer diep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Zeer-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Zeer diep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Zeer-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> getijdewateren \> Zeer diep, zwak brak getijdenwater {#sec-Zeer-diep-zwak-brak-getijdenwater}

#### Aquatisch \> getijdewateren \> Zoet aangetakte plas {#sec-Zoet-aangetakte-plas}

#### Aquatisch \> getijdewateren \> Zoet getijdenwater {#sec-Zoet-getijdenwater}

#### Aquatisch \> getijdewateren \> Zoet water achter vooroever {#sec-Zoet-water-achter-vooroever}

#### Aquatisch \> getijdewateren \> Zwak brak getijdenwater {#sec-Zwak-brak-getijdenwater}

### Aquatisch \> meren {#sec-meren}

De indeling resulteert voor de meren in 12 ecotopen en 14 eco-elementen.
De meren waarop deze indeling van toepassing is zijn Usselmeer,
Markermeer (inclusief Gouwzee en IJmeer), Zwarte Meer, Ketelmeer,
Vossemeer, Drontermeer, Veluwemeer, Wolderwijd, Nuldernauw,
Nijkerkernauw, Eemmeer, Gooimeer in het 'natte hart' en het Volkerak en
Zoommeer in het Deltagebied. \`\`\`

Aanwezigheid van dynamiek is beperkt en vooral in de vorm van sedimen-
tatie en transportprocessen. Het is niet onderscheidend voor ecotopen,
maar vertoont wel een relatie met bodemtype. Slib wordt vooral
aangetroffen op plaatsten waar sedimentatie overheerst. Het Ketelmeer en
in mindere mate het Eemmeer onderscheiden zich van de andere systemen
als gevolg van een veel kortere verblijftijd van het water. Dit
resulteert ook in ecologische verschillen, zoals de aanwezigheid van de
'rivier-kiezelwier' Stephanodiscus hantzschii en een groter aandeel
raderdieren in het zooplankton. Voorals- nog is dit geen aanleiding
geweest om hiervoor aparte ecotopen te maken.

```         
```

De eco-elementen liggen vooral in de ondiepere delen. Eco-elementen
worden gevormd door aanwezigheid van driehoeksmosselen en vegetatie.
Kranswieren en fonteinkruiden worden aangetroffen op zandbodems. terwijl
Nymphaeiden meestal te vinden zijn op kleibodems. Bij slib worden veelal
geen waterplanten aangetroffen. Door de aanwezigheid van driehoeks-
mosselen of vegetatie wordt de (invloed van) dynamiek verminderd.

##### Aquatisch \> meren \> Zeer diep water {#sec-Zeer-diep-water}

De ecotoopklasse zeer diep water omvat alle delen die permanent, dat wil
zeggen bij een gemiddeld zomerpeil, dieper zijn dan 5 meter. De klasse
omvat een ecotoop.

##### Aquatisch \> meren \> Diep water {#sec-Diep-water}

De ecotoopklasse diep water omvat alle delen die permanent, dat wil
zeggen bij gemiddeld zomerpeil, tussen de 3 en 5 meter diep zijn.

#### Aquatisch \> meren \> Matig diep water {#sec-Matig-diep-water}

De ecotoopklasse matig diep water omvat alle delen die permanent, dat
wil zeggen bij gemiddeld zomerpeil, tussen de 1 en 3 meter diep zijn.
Deze twee klassen omvatten elk vier ecotopen op basis van verschil in
bodemtype.

#### Aquatisch \> meren \> Ondiep water {#sec-Ondiep-water}

De ecotoopklasse ondiep water omvat alle delen die permanent, dat wil
zeggen bij gemiddeld zomerpeil, ondieper zijn dan 1 meter maar dieper
dan 0,3 meter. De klasse omvat slechts drie ecotopen, daar kleibodem
door erosie verwordt tot slib. De stroomsnelheid van alle klassen
varieert van stagnant tot stromend.

### Aquatisch \> rivieren {#sec-rivieren}

#### Aquatisch \> rivieren \> Diep zomerbed {#sec-Diep-zomerbed}

#### Aquatisch \> rivieren \> Diepe eenzijdig aangetakte nevengeul {#sec-Diepe-eenzijdig-aangetakte-nevengeul}

#### Aquatisch \> rivieren \> Diepe nevengeul {#sec-Diepe-nevengeul}

#### Aquatisch \> rivieren \> Matig diep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Matig-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Matig diep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Matig-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Matig diep zomerbed {#sec-Matig-diep-zomerbed}

#### Aquatisch \> rivieren \> Matig diepe eenzijdig aangetakte nevengeul {#sec-Matig-diepe-eenzijdig-aangetakte-nevengeul}

#### Aquatisch \> rivieren \> Matig diepe nevengeul {#sec-Matig-diepe-nevengeul}

#### Aquatisch \> rivieren \> Ondiep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Ondiep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Ondiep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Ondiep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Ondiep zomerbed {#sec-Ondiep-zomerbed}

#### Aquatisch \> rivieren \> Ondiepe eenzijdig aangetakte nevengeul {#sec-Ondiepe-eenzijdig-aangetakte-nevengeul}

#### Aquatisch \> rivieren \> Ondiepe nevengeul {#sec-Ondiepe-nevengeul}

#### Aquatisch \> rivieren \> Rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Rivierbegeleidend water (\</\> 20 d/j overstroomd) {#sec-Rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Zeer diep rivierbegeleidend water (\< 20 d/j overstroomd) {#sec-Zeer-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

#### Aquatisch \> rivieren \> Zeer diep rivierbegeleidend water (\> 20 d/j overstroomd) {#sec-Zeer-diep-rivierbegeleidend-water-20-d-j-overstroomd-}

# Ecotopenbeschrijving oever {#sec-Oever}

## Oever \> rivieren {#sec-rivieren}

### Oever \> rivieren \> Uiterwaard akker {#sec-Uiterwaard-akker}

UA-1 Hoge uiterwaard akker

Tot dit ecotoop worden alle bouwlanden, zowel kaal als begroeid, in de zone van de hoge uiterwaard
gerekend. Akkers worden gekenmerkt door een hoge gebruiksdynamiek (intensief beheer) en worden
vaak (zwaar) bemest. Ook kwekerijen (zoals rozen en bessenkwekerijen, die veel voorkomen langs de
onbedijkte maas worden tot dit ecotoop gerekend.
De ecologische betekenis van deze akkers is in grote mate afhankelijk van het gevoerde
landbouwkundig beheer. De soortensamenstelling van de vegetatie is veelal zeer beperkt, en is te
beschouwen als een verarmde variant van de uiterwaardruigte.
Afhankelijk van het beheer kan een aantal karakteristieke soorten voorkomen.Enkele voorbeelden zijn
bekend van akkers met bijzondere kruiden, onder ander Cortenoever langs de IJssel, waar Groot
spiegelklokje en Handjes ereprijs groeien.Bij een relatief extensief beheer, waarbij ruimte is voor
overstaande randvegetaties en verlaten hoekjes kunnen de Gele kwikstaart, Veldleeuwerik, Patrijs en
Kwartelkoning in lage aantallen aangetroffen worden.

#### Oever \> rivieren \> Uiterwaard bebouwd {#sec-Uiterwaard-bebouwd}

UA-2 Bebouwde hoge uiterwaard

Dit ecotoop omvat bebouwde en verharde (b.v. bedrijfsterrein, parkeerterrein en wegen) terreinen.Binnen dit
ecotoop kunnen verschillende ruigte- en pionierbegroeiingen worden aangetroffen. De ecologische


betekenis en samenstelling kunnen sterk per locatie verschillen, afhankelijk van de lokale bebouwing,
het type verharding en de intensiteit waarmee het terrein wordt gebruikt. Veelal kan deze gezien
worden als een afgeleide van de uiterwaardruigte.

#### Oever \> rivieren \> Uiterwaard grasland (natuurlijk of productie) {#sec-Uiterwaard-grasland-natuurlijk-of-productie-}

UG-1 Natuurlijk uiterwaardgrasland

In tegenstelling tot de productiegraslanden kent dit ecotoop (indien sprake is van begrazing) een
extensieve vorm van begrazingsbeheer en dientengevolge een geringere mestgift.

Het ecotoop omvat alle typische vormen van glanshaverhooilanden en kamgrasweiden. Voorbeelden
vanvoorkomende plantensoorten in kamgrasweiden zijn Brede, Liggende en Vroege ereprijs, Veldsalie,
Kluwenklokje, Kamgras, Knopig doornzaad, Veldgerst. Begeleidende soorten van glanshaverhooilanden
zijn: Goudhaver, Roodzwenkgras, Gele morgenster, Groot streepzaad, Glad walstro en Gewone
hoornbloem. Meer bijzondere soorten zijn de Gewone agrimonie, Karwijselie en Oosterse morgenster
De bloemrijke vegetaties zijn vaak rijk aan insecten. De Veldparelmoervlinder is één van de vele
vlindersoorten die zich hier voortplant. De soortenrijke vegetaties zijn van belang voor grondbroedende
vogelsoorten als Patrijs, Grutto, Kievit, Tureluur, Goudplevier, Veldleeuwerik, Gele kwikstaart en
Kwartelkoning. Bij een behoorlijke omvang kan het ecotoop een belangrijke functie hebben als
foerageergebied voor ganzen en zwanen. Het is een geliefd biotoop voor kleine zoogdieren, zoals de
Rosse vleermuis en de Das.

#### Oever \> rivieren \> Uiterwaard hoogstamboomgaard {#sec-Uiterwaard-hoogstamboomgaard}

#### Oever \> rivieren \> Uiterwaard laagstamboomgaard {#sec-Uiterwaard-laagstamboomgaard}

#### Oever \> rivieren \> Uiterwaard natuurlijk bos {#sec-Uiterwaard-natuurlijk-bos}

UB-1 Natuurlijk uiterwaardbos

Tot de natuurlijke bossen worden alle bossen gerekend met een nagenoeg natuurlijke tot half
natuurlijke gebruiksdynamiek. Twee soorten natuurlijke bossen kunnen voorkomen in de hoge
uiterwaarden: het zachthoutooibos en het hardhoutooibos.
Het hoger gelegen oeverwal zachthoutooibos vormt veelal een ontwikkelingsfase in de successie naar
hardhoutooibos.Botanisch gezien zijn de zachthoutooibossen niet soortenrijk, maar met wilgen als
Bittere wilg, Amandelwilg en met name Schietwilg is de vegetatie wel karakteristiek. De boomlaag
bestaat uit Schietwilgen en Zwarte populieren. Vaak ontwikkelt zich een struiklaag bestaande uit
Sleedoorn en Meidoorn. Lianen als Haagwinde en Bosrank zijn veelvoorkomend, terwijl in de kruidlaag
ruigtekruiden domineren als Reuzenbalsemien, Fluitenkruid,Grote engelwortel en Grote brandnetel.
Reigersoorten (Kleine zilverreiger, Blauwe reiger), Kwak, Zomertortel, Aalscholver, Nachtegaal,
Buidelmees en Wielwaal slapen en broeden hier, de Otter schuilt er. De Visarend en Zeearend kunnen
het ecotoop gebruikenals rustplaats. In en op zachthoutooibossen komt een grote rijkdom aan
macrofaunasoorten voor, waaronder de Muskusboktor.

Hardhoutooibossen zijn zelden overstroomde, hoger gelegen rivierbegeleidende bossen. Het percentage
zachthoutsoorten is lager dan 50%. Het hardhoutooibos is een structuurrijk bos, met een goed
ontwikkelde struiklaag, meestal twee boomlagen en een weelderig ontwikkelde bodemflora. De
boomlaag bestaat onder andere uit Spaanse aak, Winterlinde, Gewone esdoorn, Es, Zomereik, Witte
abeel enGladde iep. In de struiklaag zijn Eenstijlige meidoorn, Sleedoorn, Rode kornoelje en Wilde
kardinaalsmuts te vinden. Kenmerkend voor dit bostype zijn de vele klim- en slingerplanten; Bosrank,
Besanjelier, Warkruid en Hop zijn daar voorbeelden van. In de kruidlaag komen daarnaast veel geofyten
voor, waaronder (bijzondere) soorten als Slangelook en Gewone vogelmelk.
Voor vogels als Zwarte Wouw, Wespendief en Zwarte ooivaar vormen de zelden overstroomde bossen
een geschikt biotoop. Kleine en Middelste bonte specht, Blauwe reiger, Kwak, Appelvink, Boomklever,
Zomertortel en Wielewaal vinden er een broed- en rustgebied. Veel (kleine) zoogdieren, amfibieën en
(bodem)insecten velen zich hier thuis, onder andere Ree, Das, Rosse vleermuis en Ruige
dwergvleermuis.

#### Oever \> rivieren \> Uiterwaard natuurlijk grasland {#sec-Uiterwaard-natuurlijk-grasland}

#### Oever \> rivieren \> Uiterwaard onbegroeid (antropogeen) {#sec-Uiterwaard-onbegroeid-antropogeen-}

#### Oever \> rivieren \> Uiterwaard productiebos {#sec-Uiterwaard-productiebos}

UB-3 Uiterwaardproductiebos


Dit ecotoop wordt beheerd ten behoeve van de houtproductie; de boomlaag is in het algemeen
éénsoortig. Veel voorkomende productiesoorten zijn Gewone es,Grove den en Zomereik. In meer
vochtige omstandigheden kunnen populieren en wilgen aangeplant worden. In dat geval ontstaan er
ruigten met nitrofiele soorten als Dauwbraam en Grote brandnetel. Een bijzondere vorm zijn de
grienden, bestaande uit (knot)wilgen. Met hun dichte, ruige ondergroei trekken ze hoge aantallen
kleine zoogdieren (muizen) en bodemfauna (spinnen) aan en vormen een geschikt broedhabitat voor
water- en bosvogels. De kruid- en struiklaag van de overige productiebostypen zijn relatief soort- en
structuurarm. Hakhoutbossen (es) worden ook tot het ecotoop productiebos gerekend, evenals
boomgaarden en laanbomen. Grienden, veel aangetroffen in het getijderivierengebied, bestaan uit
aangeplante hak- of snijwilgen, en vallen eveneens onder productiebos. Verlaten grienden waarbij het
regelmatige patroon is verdwenen worden niet gerekend tot dit ecotoop, maar vallen onder het
zachthoutooibos.

#### Oever \> rivieren \> Uiterwaard productiegrasland {#sec-Uiterwaard-productiegrasland}

UG-2 Uiterwaard productiegrasland

Het ecotoop productiegrasland staat onder intense agrarische druk en de bemestingsgraad is hoog.
Over het algemeen zijn het structuur- en soortenarme graslanden. De vegetatie wordt gedomineerd
door ingezaaide grassoorten zoals Engels raaigras en kent een beperkt aantal kruidachtige soorten.
Indien de mestgift matig is, kan een intensief bodemleven ontstaan, vol wormen en insecten die dienen
als voedsel voor vogels. In dat geval kunnen de graslanden een grote betekenis hebben als foerageer-
en broedgebied voor weidevogels. Bij een behoorlijke omvang heeft het ecotoop een belangrijke functie
als foerageergebied voor overwinteraars als ganzen (Rotgans, Kolgans, Brandgans en Grauwe gans),
zwanen (Kleine zwaan en Knobbelzwaan) en de Goudplevier.
Golfbanen en recreatieterreinen worden ook tot deze ecotoopgroep gerekend.

#### Oever \> rivieren \> Uiterwaard riet {#sec-Uiterwaard-riet}

#### Oever \> rivieren \> Uiterwaard ruigte {#sec-Uiterwaard-ruigte}

R-1 Uiterwaardruigte

Uiterwaardruigtes kunnen zowel structuurarm als structuurrijk zijn, afhankelijk van de intensiteit van het
beheer. De soortenrijke variant bestaat uit twee- en meerjarige ruigtekruiden, die al dan niet afhankelijk
zijn van grondwater. Voorbeelden van voorkomende plantensoorten zijn Poelruit, Gewone wederik,
Grote valeriaan, Akkerdistel, Boeren wormkruid, Harig wilgeroosje, Moeraskruiskruid en in nattere
omstandigheden ook het Rivierkruiskruid.
Op meer verrijkte bodems ontstaan soort- en structuurarmere vegetaties. De soort- en structuurrijkdom
neemt vaak ook af ten gevolge van voortschrijdende successie.Bij een soortenarme ruigte (biezengors
of rietgors) domineert vaak één soort, zoals bij rietzomen met hoogopgaand, vitaal riet. Voorbeelden
van andere dominerende soorten zijnGrote brandnetel, Ridderzuring, Dauwbraam, Smalbladige asters
en ruige grassen als Rietgras, Kweek en Kropaar. De ruigten fungeren als broedgelegenheid voor
soorten als Blauwborst, Bosrietzanger, Roodborst tapuit, Grasmus, Rietgors, Sprinkhaanrietzanger en
Kwartelkoning. Het is tevens een belangrijk ecotoop voor zoogdieren en insecten.

#### Oever \> rivieren \> Uiterwaard struweel {#sec-Uiterwaard-struweel}

UB-2 Uiterwaardstruweel

Het onderscheid tussen bos en struweel ligt bij de gemiddelde planthoogte: hoger dan 5 meter spreken
we van bos, lager van struweel. Ook in de struwelen is ‘zachthout’ en een ‘hardhout’-type te
onderscheiden, waarbij de tweede de eerste opvolgt in de successie.
Zachthoutstruweel kenmerkt zich door de dominantie van struikwilgen als Katwilg, Amandelwilg en
Bittere wilg. Vaak komen ook jonge Schietwilgen en Zwarte populieren voor. De kruidlaag is vaak
spaarzaam en bestaat uit pionierruigtekruiden als Gele waterkers en Brandnetel. De struwelen bieden
foerageer- en broedgelegenheid aan kleine zangvogels als Tjiftjaf en Buidelmees.
De periodiek overstroomde doornstruwelen bestaan uit soorten uit de struiklaag van het
hardhoutooibos, zoals Eenstijlige meidoorn, Sleedoorn, Kardinaalsmuts, Gewone vlier, Lijsterbes,
Hondsroos en Dauwbraam. In het overgangsgebied met het water van de zoute Delta komen
duinstruwelen voor met struiksoorten als Duindoorn, Wegedoorn, Wilde liguster en Zuurbes. De
kruidlaag van doornstruwelen is soortenarm, met onder andere Duinriet, Akkerdistel, Grote brandnetel
en Kropaar. Struwelen zijn waardevol voor vogels als de Grauwe klauwier, Grasmus, Braamsluiper,
Geelgors, Roodborsttapuit, Nachtegaal en Bosrietzanger enroofvogels als de Slechtvalk en Torenvalk.
Ze zijn van belang voor tal van insecten waaronder vlindersoorten (Kleine ijsvogelvlinder,
Sleedoornpage) en bieden een schuil- en overwinteringsplaats aan amfibieën (Kamsalamander,
Boomkikker), kleine zoogdieren(Das, Wezel, Hermelijn) en reptielen (Ringslang, Levendbarende
hagedis).

#### Oever \> rivieren \> Uiterwaard vegetatie met lage bedekking (5 - 25%) {#sec-Uiterwaard-vegetatie-met-lage-bedekking-5-25-}

#### Oever \> rivieren \> Akker in oever {#sec-Akker-in-oever}

#### Oever \> rivieren \> Dynamisch zoet tot zwak brak ondiep water {#sec-Dynamisch-zoet-tot-zwak-brak-ondiep-water}

#### Oever \> rivieren \> Grasland in oever {#sec-Grasland-in-oever}

#### Oever \> rivieren \> Grindbanken {#sec-Grindbanken}

#### Oever \> rivieren \> Hard substraat in laag littoraal zout getijdenwater {#sec-Hard-substraat-in-laag-littoraal-zout-getijdenwater}

#### Oever \> rivieren \> Helofytenmoeras (riet/moerasplanten) in oever {#sec-Helofytenmoeras-riet-moerasplanten-in-oever}

#### Oever \> rivieren \> Hoogstamboomgaard in oever {#sec-Hoogstamboomgaard-in-oever}

#### Oever \> rivieren \> Laagstamboomgaard in oever {#sec-Laagstamboomgaard-in-oever}

#### Oever \> rivieren \> Matig dynamisch hard substraat op de buitenberm onder invloed van getijdenwater {#sec-Matig-dynamisch-hard-substraat-op-de-buitenberm-onder-invloed-van-getijdenwater}

#### Oever \> rivieren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water}

#### Oever \> rivieren \> Moerasruigte in oever {#sec-Moerasruigte-in-oever}

#### Oever \> rivieren \> Moerasruigte/gorsruigte in oever {#sec-Moerasruigte-gorsruigte-in-oever}

#### Oever \> rivieren \> Moerassig overstromingsgrasland in oever {#sec-Moerassig-overstromingsgrasland-in-oever}

#### Oever \> rivieren \> Moerassig overstromingsgrasland/productiegrasland in oever {#sec-Moerassig-overstromingsgrasland-productiegrasland-in-oever}

#### Oever \> rivieren \> Moerassig structuurrijk overstromingsgrasland {#sec-Moerassig-structuurrijk-overstromingsgrasland}

#### Oever \> rivieren \> Onbegroeid (antropogeen) in oever {#sec-Onbegroeid-antropogeen-in-oever}
OK-1 Onbegroeide oeverwal

Het (nagenoeg) ontbreken van begroeiing duidt op een hoogdynamisch milieu óf op een tijdelijke
verstoring als gevolg van een menselijke ingreep. In de eerste situatie betreft het een oeverwal met
zandsedimentatie tijdens hoogwater of een rivierduin met zandverstuiving; in de tweede gaat het
bijvoorbeeld om een zanddepot of een vergraving, veelal een tijdelijke, onnatuurlijke situatie.
Zanddepots en vergavingen worden dan ook gerekend tot het ‘rest’ecotoop, om onderscheid te kunnen
maken met kale delen die het gevolg zijn van een natuurlijke dynamiek met veel hogere
natuurwaarden.
Het ecotoop onbegroeide oeverwal wordt gekenmerkt door geen begroeiing of een zeer open
kruidenrijke vegetatie (bedekking < 25%). Dit karakter is doorgaans van tijdelijke aard, als gevolg van
recent ontstane of van vegetatie ontdane locaties, dan wel onstabiele standplaatsen. De
kruidenvegetatie wordt gedomineerd door één- en tweejarige soorten, of meerjarige soorten met een groot vegetatief voortplantingsvermogen. De ecologische samenstelling en betekenis kan sterk per locatie verschillen.
Kalegrondbroeders vinden hier een nestgelegenheid, zolang de successie nog niet in een
vergevorderd stadium is; Kleine plevier, Visdief, Kluut en Bontbekplevier zijn hier voorbeelden van.
Ook kan het ecotoop zeer rijk zijn aan (bijzondere soorten) ongewervelde dieren, zoals de
Grindwolfspin.De droge en zandige milieus zijn van belang voor Zandhagedis, Rugstreeppad,
zandloopkevers, Mierenleeuw en graafwespen.

#### Oever \> rivieren \> Productiebos in oever {#sec-Productiebos-in-oever}

#### Oever \> rivieren \> Productiegrasland in oever {#sec-Productiegrasland-in-oever}

#### Oever \> rivieren \> Soortenarme helofytenvegetatie in ondiep water {#sec-Soortenarme-helofytenvegetatie-in-ondiep-water}

#### Oever \> rivieren \> Vegetatie met lage bedekking (5 - 25%) in oever {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever}

#### Oever \> rivieren \> Zachthout ooibos in oever {#sec-Zachthout-ooibos-in-oever}

#### Oever \> rivieren \> Zachthout struweel in oever {#sec-Zachthout-struweel-in-oever}

#### Oever \> rivieren \> Zoete zandplaten {#sec-Zoete-zandplaten}

#### Oever \> rivieren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water/overstromingsvrij bebouwd {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water-overstromingsvrij-bebouwd}

#### Oever \> rivieren \> Moerasruigte/gorsruigte/overstromingsvrije ruigte {#sec-Moerasruigte-gorsruigte-overstromingsvrije-ruigte}

#### Oever \> rivieren \> Oever of overstromingsvrij grasland (natuurlijk of productie) {#sec-Oever-of-overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> rivieren \> Oever of overstromingsvrij natuurlijk bos {#sec-Oever-of-overstromingsvrij-natuurlijk-bos}

#### Oever \> rivieren \> Oever of overstromingsvrij natuurlijk grasland {#sec-Oever-of-overstromingsvrij-natuurlijk-grasland}

#### Oever \> rivieren \> Oever of overstromingsvrij productiebos {#sec-Oever-of-overstromingsvrij-productiebos}

#### Oever \> rivieren \> Oever of overstromingsvrij productiegrasland {#sec-Oever-of-overstromingsvrij-productiegrasland}

#### Oever \> rivieren \> Oever of overstromingsvrij struweel {#sec-Oever-of-overstromingsvrij-struweel}

#### Oever \> rivieren \> Vegetatie met lage bedekking (5 - 25%) in oever of overstromingsvrij {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever-of-overstromingsvrij}

### Oever \> rivieren \> Overzicht Oeverwal Ecotopen

De oeverwalzone komt alleen voor langs de grote rivieren en de
bovenstroomse delen van de Rijn- Maasmonding (met name de Afgedamde Maas
en de Lek) die gedomineerd worden door rivierinvloeden. De oeverwalzone
kenmerkt zich door een hoge morfodynamiek. Wanneer tijdens hoge afvoeren
het rivierwater de uitwaard instroomt, neemt de stroomsnelheid snel af,
waardoor het meegevoerde sediment kan uitzakken en sedimenteert. In
eerste instantie zal dit het zwaarste materiaal zijn (in Nederland
veelal zand) waardoor oeverwallen kunnen ontstaan. Oeverwallen ontstaan
veelal in binnenbochten, door aanzanding van de uiterwaard direct naast
de stroomgeul. Dit proces heeft al plaats bij een gemiddelde afvoer,
maar wordt tijdens hoogwater versterkt door een verhoogd sedimentaanbod.
Een speciale vorm van zandafzettingen in de uiterwaard zijn de
rivierduinen. Deze ontstaan door het uitwaaien van droge (kribvak-)
stranden. Het ontstaan van rivierduinen is mede afhankelijk van de
aanwezigheid van dergelijke stranden en de ligging hiervan ten
opzichtevan de heersende windrichting. Vooral langs de Waal zijn nog
potentiële locaties waar rivierduinen kunnen ontstaan. In Nederland is
nog maar één levend rivierduin: het Millingerduin.

Afhankelijk van de hoogte van het gesedimenteerde zandpakket kent de
oeverwal een hoge tot matige hydrodynamiek. Gelet op de aansluiting met
de voorliggende oeverzone kent de oeverwalzone een gemiddelde
overstromingsduur tot maximaal 50 dagen per jaar.

Als gevolg van het zandige substraat op oeverwal en rivierduin ontstaat
op deze voedselarme milieus vaak een karakteristieke vegetatie. Als
gevolg van met name het gevoerde beheer kunnen op grond van de
vegetatiestructuur vijf ecotoopgroepen onderscheiden worden die
uiteindelijk leiden tot negen ecotopen (tabel 5). Indien nodigvoor een
goed begrip wordt navolgend per ecotoop nog aanvullende informatie
aangaande de landschappelijke zonering gepresenteerd.

Zone Ecotoopgroep Ecotoop Code Indelingskenmerk H M B Oeverwal
antropogeen(A) oeverwal akker OA-1 1r S I (O) bebouwde oeverwal OA-2 1r
S K onbegroeid (K) onbegroeide oeverwal OK-1 1r S N/E grasland (G)
natuurlijk oeverwalgrasland OG-1 1r S N/E oeverwal productiegrasland
OG-2 1r S I ruigte (R) oeverwal ruigte O R-1 1r S N/E bos (B) oeverwal
natuurlijk bos OB-1 1r S N/E oeverwalstruweel OB-2 1r S N/E oeverwal
productiebos OB-3 1r S I

*H = hydrologie: 1 = periodiek tot zelden overstroomd, 2 =
overstromingsvrij ( de r staat voor rivieren) M = mechanische dynamiek:
S = sterk dynamisch, M = matig dynamisch, G = gering dynamisch B =
gebruik/beheer: I = intensief, E = extensief, N = nauwelijks tot geen
beheer; K = kunstmatig hard substraat* (zie tevens tabellen 2, 3 en 4)

### 4.3 ECOTOPEN VAN DE HOGEUITERWAARD(U)..................................................................................

De hoge uiterwaard komt alleen voor langs de grote rivieren en delen van de Rijn-Maasmonding
(benedenrivierengebied) die gedomineerd worden door rivierinvloeden. In vergelijking tot de hiervoor
beschreven oeverwalzone is de hydrologische karakteristiek van de hoge uiterwaard gelijk. Het verschil
in ecotopen van de hoge uiterwaard wordt bepaald door een lagere morfodynamiek.

Als gevolg van met name het gevoerde beheer kunnen op grond van de vegetatiestructuur vier
ecotoopgroepen onderscheiden worden die uiteindelijk leiden tot acht ecotopen (tabel 6). Indien nodig
voor een goed begrip wordt navolgend per ecotoop nog aanvullende informatie aangaande de
landschappelijke zonering gepresenteerd.


Zone Ecotoopgroep Ecotoop Code Indelingskenmerk
H M B
Hoge antropogeen (A) uiterwaardakker UA-1 1r M/G I
uiterwaard bebouwde uiterwaard UA-2 1r M/G K
(U) grasland (G) natuurlijk uiterwaardgrasland UG-1 1r M/G N/E
uiterwaard productiegrasland UG-2 1r M/G I
ruigte (R) uiterwaard ruigte UR-1 1r M/G N/E
bos (B) natuurlijk uiterwaardbos UB-1 1r M/G N/E
uiterwaardstruweel UB-2 1r M/G N/E
uiterwaard productiebos UB-3 1r M I

_H = hydrologie: 1 = periodiek tot zelden overstroomd, 2 = overstromingsvrij ( de r staat voor rivieren)
M = mechanische dynamiek: S = sterk dynamisch, M = matig dynamisch, G = gering dynamisch
B = gebruik/beheer: I = intensief, E = extensief, N = nauwelijks tot geen beheer; K = kunstmatig hard substraat_
(zie tevens tabellen 2, 3 en 4)

#### Oever \> rivieren \> Oeverwal of uiterwaard akker {#sec-Oeverwal-of-uiterwaard-akker}

OA-1 Oeverwal akker
UA-1 Hoge uiterwaard akker

Tot dit ecotoop worden alle bouwlanden, zowel kaal als begroeid, in de
oeverwalzone gerekend. Akkers worden gekenmerkt door een hoge
gebruiksdynamiek (intensief beheer) en worden vaak (zwaar) bemest. De
ecologische betekenis van deze akkers is in grote mate afhankelijk van
het gevoerde landbouwkundig beheer. De soortensamenstelling van de
vegetatie is veelal zeer beperkt, en is te beschouwen als een verarmde
variant van de oeverwalruigte. Afhankelijk van het beheer kan een aantal
karakteristieke soorten voorkomen. Bij een relatief extensief beheer,
waarbij ruimte is voor overstaande randvegetaties en verlaten hoekjes
kunnen de Gele kwikstaart, Veldleeuwerik, Patrijs en Kwartelkoning in
lage aantallen aangetroffen worden.

#### Oever \> rivieren \> Oeverwal of uiterwaard bebouwd {#sec-Oeverwal-of-uiterwaard-bebouwd}
OA-2
UA-2 Bebouwde hoge uiterwaard

Dit ecotoop omvat bebouwde en verharde terreinen zoals bedrijfsterrein, parkeerterrein en wegen.
Binnen het ecotoop kunnen verschillende ruigte- en pionierbegroeiingen aangetroffen worden. De
ecologische betekenis en samenstelling kunnensterk per locatie verschillen, afhankelijk van de lokale
bebouwing, het type verharding en de intensiteit waarmee het terrein wordt gebruikt. Veelal kan deze
gezien worden als een afgeleide van de oeverwalruigte.

#### Oever \> rivieren \> Oeverwal of uiterwaard grasland (natuurlijk of productie) {#sec-Oeverwal-of-uiterwaard-grasland-natuurlijk-of-productie-}

OG-1 Natuurlijk oeverwalgrasland
UG-1 Natuurlijk uiterwaardgrasland

In tegenstelling tot de productiegraslanden kent dit ecotoop (indien sprake is van begrazing) een
extensieve vorm van begrazingsbeheer en dientengevolge een geringere mestgift.

Het ecotoop omvat alle typische vormen van glanshaverhooilanden en kamgrasweiden. Ook de
stroomdalgraslanden vallen eronder. Voorbeelden van voorkomende plantensoorten in kamgrasweiden
zijn Brede, Liggende en Vroege ereprijs, Veldsalie, Kluwenklokje, Kamgras, Knopig doornzaad,
Veldgerst. Begeleidende soorten van glanshaverhooilanden zijn: Goudhaver, Roodzwenkgras, Gele
morgenster, Groot streepzaad, Glad walstro en Gewone hoornbloem. Meer bijzondere soorten zijn de
Gewone agrimonie, Karwijselie en Oosterse morgenster
De bloemrijke vegetaties zijn vaak rijk aan insecten. De Veldparelmoervlinder is één van de vele
vlindersoorten die zich hier voortplant. De soortenrijke vegetaties zijn van belang voor grondbroedende
vogelsoorten als Patrijs, Grutto, Kievit, Tureluur, Goudplevier, Veldleeuwerik, Gele kwikstaart en
Kwartelkoning. Bij een behoorlijke omvang kan het ecotoop een belangrijke functie hebben als
foerageergebied voor ganzen en zwanen. Het is een geliefd biotoop voor kleine zoogdieren, zoals de
Rosse vleermuis en de Das.
Rivierduinen vormen een bijzondere groep binnen de natuurlijke oeverwalgraslanden. Hier komen vaak
opvallend veel zeldzame soorten voor. Rivierduinen kenmerken zich door een soorten- en kruidenrijke
vegetatie met plantensoorten zoals Smal fakkelgras, Echt walstro, Goudhaver, Zandhoornbloem,
Zandzegge, Zachte haver, Margriet, Kleine bevernel, Beemdkroon, Kleine ratelaar, Kleine pimpernel,
Wilde marjolein, Kruisdistel, Knikkende distel, Weidekervel en Kruisbladwalstro.


#### Oever \> rivieren \> Oeverwal of uiterwaard hoogstamboomgaard {#sec-Oeverwal-of-uiterwaard-hoogstamboomgaard}

#### Oever \> rivieren \> Oeverwal of uiterwaard laagstamboomgaard {#sec-Oeverwal-of-uiterwaard-laagstamboomgaard}

#### Oever \> rivieren \> Oeverwal of uiterwaard natuurlijk bos {#sec-Oeverwal-of-uiterwaard-natuurlijk-bos}

OB-1 Oeverwal natuurlijk bos


Tot de natuurlijke bossen worden alle bossen gerekend met een nagenoeg natuurlijke tot half
natuurlijke gebruiksdynamiek. Op de oeverwal kot over het algemeen maar één soort natuurlijk bos
voor, het zachthoutooibos; voor het ontstaan van hardhoutooibos is de overstromingsduur veelal nog
te hoog.
Botanisch gezien zijn de zachthoutooibossen niet soortenrijk, maar met wilgen als Bittere wilg,
Amandelwilg en met name Schietwilg is de vegetatie wel karakteristiek. De boomlaag bestaatuit
Schietwilgen en Zwarte populieren. Vaak ontwikkelt zich een struiklaag. Lianen als Haagwinde en
Bosrank zijn veelvoorkomend, terwijl in de kruidlaag ruigtekruiden domineren als Reuzenbalsemien,
Fluitenkruid, Grote engelwortel en Grote brandnetel.
Reigersoorten (Kleine zilverreiger, Blauwe reiger), Kwak, Zomertortel, Aalscholver, Nachtegaal,
Buidelmees en Wielwaal slapen en broeden hier, de Otter schuilt er. De Visarend en Zeearend kunnen
het ecotoop gebruiken als rustplaats. In en op zachthoutooibossenkomt een grote rijkdom aan
macrofaunasoorten voor, waaronder de Muskusboktor.


UB-1 Natuurlijk uiterwaardbos

Tot de natuurlijke bossen worden alle bossen gerekend met een nagenoeg natuurlijke tot half
natuurlijke gebruiksdynamiek. Twee soorten natuurlijke bossen kunnen voorkomen in de hoge
uiterwaarden: het zachthoutooibos en het hardhoutooibos.
Het hoger gelegen oeverwal zachthoutooibos vormt veelal een ontwikkelingsfase in de successie naar
hardhoutooibos.Botanisch gezien zijn de zachthoutooibossen niet soortenrijk, maar met wilgen als
Bittere wilg, Amandelwilg en met name Schietwilg is de vegetatie wel karakteristiek. De boomlaag
bestaat uit Schietwilgen en Zwarte populieren. Vaak ontwikkelt zich een struiklaag bestaande uit
Sleedoorn en Meidoorn. Lianen als Haagwinde en Bosrank zijn veelvoorkomend, terwijl in de kruidlaag
ruigtekruiden domineren als Reuzenbalsemien, Fluitenkruid,Grote engelwortel en Grote brandnetel.
Reigersoorten (Kleine zilverreiger, Blauwe reiger), Kwak, Zomertortel, Aalscholver, Nachtegaal,
Buidelmees en Wielwaal slapen en broeden hier, de Otter schuilt er. De Visarend en Zeearend kunnen
het ecotoop gebruikenals rustplaats. In en op zachthoutooibossen komt een grote rijkdom aan
macrofaunasoorten voor, waaronder de Muskusboktor.

Hardhoutooibossen zijn zelden overstroomde, hoger gelegen rivierbegeleidende bossen. Het percentage
zachthoutsoorten is lager dan 50%. Het hardhoutooibos is een structuurrijk bos, met een goed
ontwikkelde struiklaag, meestal twee boomlagen en een weelderig ontwikkelde bodemflora. De
boomlaag bestaat onder andere uit Spaanse aak, Winterlinde, Gewone esdoorn, Es, Zomereik, Witte
abeel enGladde iep. In de struiklaag zijn Eenstijlige meidoorn, Sleedoorn, Rode kornoelje en Wilde
kardinaalsmuts te vinden. Kenmerkend voor dit bostype zijn de vele klim- en slingerplanten; Bosrank,
Besanjelier, Warkruid en Hop zijn daar voorbeelden van. In de kruidlaag komen daarnaast veel geofyten
voor, waaronder (bijzondere) soorten als Slangelook en Gewone vogelmelk.
Voor vogels als Zwarte Wouw, Wespendief en Zwarte ooivaar vormen de zelden overstroomde bossen
een geschikt biotoop. Kleine en Middelste bonte specht, Blauwe reiger, Kwak, Appelvink, Boomklever,
Zomertortel en Wielewaal vinden er een broed- en rustgebied. Veel (kleine) zoogdieren, amfibieën en
(bodem)insecten velen zich hier thuis, onder andere Ree, Das, Rosse vleermuis en Ruige
dwergvleermuis.


#### Oever \> rivieren \> Oeverwal of uiterwaard natuurlijk grasland {#sec-Oeverwal-of-uiterwaard-natuurlijk-grasland}

#### Oever \> rivieren \> Oeverwal of uiterwaard onbegroeid (antropogeen) {#sec-Oeverwal-of-uiterwaard-onbegroeid-antropogeen-}

#### Oever \> rivieren \> Oeverwal of uiterwaard onbegroeid (natuurlijk) {#sec-Oeverwal-of-uiterwaard-onberoeid-natuurlijk-}

#### Oever \> rivieren \> Oeverwal of uiterwaard productiebos {#sec-Oeverwal-of-uiterwaard-productiebos}

OB-3 Oeverwal productiebos
UB-3 Uiterwaardproductiebos

Dit ecotoop wordt beheerd ten behoeve van de houtproductie; de boomlaag bestaat over het algemeen
uit één soort. Veel voorkomende productiesoorten zijn Gewone es, Grove den en Zomereik. In meer
vochtige omstandigheden kunnen populieren en wilgenaangeplant worden. In dat geval ontstaan er
ruigten met nitrofiele soorten als Dauwbraam en Grote brandnetel. Een bijzondere vorm zijn de
grienden, bestaande uit (knot)wilgen. Met hun dichte, ruige ondergroei trekken ze hoge aantallen
kleine zoogdieren (muizen) en bodemfauna (spinnen) aan en vormen een geschikt broedhabitat voor
water- en bosvogels. De kruid- en struiklaag van de overige productiebostypen zijn relatief soort- en
structuurarm. Hakhoutbossen (es) worden ook tot het ecotoop productiebos gerekend, evenals
(fruit)boomgaarden en laanbomen. Grienden bestaan uit aangeplante hak- of snijwilgen, en vallen
eveneens onder productiebos. Verlaten grienden waarbij het regelmatige patroon is verdwenen worden
niet gerekend tot dit ecotoop, maar vallen onderhet zachthoutooibos.

#### Oever \> rivieren \> Oeverwal of uiterwaard productiegrasland {#sec-Oeverwal-of-uiterwaard-productiegrasland}
OG-2 Oeverwal productiegrasland
UG-2 Uiterwaard productiegrasland

Het ecotoop productiegrasland staat onder intense agrarische druk en de bemestingsgraad is hoog.
Over het algemeen zijn het structuur- en soortenarme graslanden. De vegetatie wordt gedomineerd
door ingezaaide grassoorten zoals Engels raaigras en kent een beperkt aantal kruidachtige soorten.
Indien de mestgift matig is, kan een intensief bodemleven ontstaan, vol wormen en insecten die dienen
als voedsel voor vogels. In dat geval kunnen de graslanden een grote betekenis hebben als foerageer-
en broedgebied voorweidevogels. Bij een behoorlijke omvang heeft het ecotoop een belangrijke functie
als foerageergebied voor overwinteraars als ganzen (Rotgans, Kolgans, Brandgans en Grauwe gans),
zwanen (Kleine zwaan en Knobbelzwaan) en de Goudplevier.

Golfbanen en recreatieterreinen worden ook tot deze ecotoopgroep gerekend.





#### Oever \> rivieren \> Oeverwal of uiterwaard ruigte {#sec-Oeverwal-of-uiterwaard-ruigte}

OR-1 Oeverwal ruigte
UR-1 Uiterwaardruigte

Oeverwalruigtes kunnen zowel structuurarm als structuurrijk zijn, afhankelijk van de intensiteit van het
beheer. De soortenrijke variantbestaat uit twee- en meerjarige ruigtekruiden, die al dan niet afhankelijk
zijn van grondwater. Voorbeelden van voorkomende plantensoorten zijn Poelruit, Gewone wederik,
Grote valeriaan, Akkerdistel, Boeren wormkruid, Harig wilgeroosje, Moeraskruiskruid enin nattere
omstandigheden ook het Rivierkruiskruid.
Op meer verrijkte bodems ontstaan soort- en structuurarmere vegetaties. De soort- en structuurrijkdom
neemt vaak ook af ten gevolge van voortschrijdende successie.Bij een soortenarme ruigte (biezengors
of rietgors) domineert vaak één soort, zoals bij rietzomen met hoogopgaand, vitaal riet. Voorbeelden
van andere dominerende soorten zijnGrote brandnetel, Ridderzuring, Dauwbraam, Smalbladige asters
en ruige grassen als Rietgras, Kweek en Kropaar
De ruigten fungeren als broedgelegenheid voor soorten als Blauwborst, Bosrietzanger, Roodborst
tapuit, Grasmus, Rietgors, Sprinkhaanrietzanger en Kwartelkoning. Het is tevens een belangrijk ecotoop
voor zoogdieren en insecten.

#### Oever \> rivieren \> Oeverwal of uiterwaard struweel {#sec-Oeverwal-of-uiterwaard-struweel}

OB-2 Oeverwal struweel

Het onderscheid tussen bos en struweel ligt bij de gemiddelde planthoogte: hoger dan 5 meter spreken
we van bos, lager van struweel. Ook in de struwelen is ‘zachthout’ en een ‘hardhout’-type te
onderscheiden; op de oeverwal is er veelal sprake van zachthoutstruweel.
Zachthoutstruweel kenmerkt zich door de dominantie van struikwilgen als Katwilg, Amandelwilg en
Bittere wilg. Vaak komen ook jonge Schietwilgen en Zwarte populieren voor. De kruidlaag is vaak
spaarzaam en bestaat uit pionierruigtekruiden als Gele waterkers en Brandnetel. De struwelen bieden
foerageer- en broedgelegenheid aan kleine zangvogels als Tjiftjaf en Buidelmees.

UB-2 Uiterwaardstruweel

Het onderscheid tussen bos en struweel ligt bij de gemiddelde planthoogte: hoger dan 5 meter spreken
we van bos, lager van struweel. Ook in de struwelen is ‘zachthout’ en een ‘hardhout’-type te
onderscheiden, waarbij de tweede de eerste opvolgt in de successie.
Zachthoutstruweel kenmerkt zich door de dominantie van struikwilgen als Katwilg, Amandelwilg en
Bittere wilg. Vaak komen ook jonge Schietwilgen en Zwarte populieren voor. De kruidlaag is vaak
spaarzaam en bestaat uit pionierruigtekruiden als Gele waterkers en Brandnetel. De struwelen bieden
foerageer- en broedgelegenheid aan kleine zangvogels als Tjiftjaf en Buidelmees.
De periodiek overstroomde doornstruwelen bestaan uit soorten uit de struiklaag van het
hardhoutooibos, zoals Eenstijlige meidoorn, Sleedoorn, Kardinaalsmuts, Gewone vlier, Lijsterbes,
Hondsroos en Dauwbraam. In het overgangsgebied met het water van de zoute Delta komen
duinstruwelen voor met struiksoorten als Duindoorn, Wegedoorn, Wilde liguster en Zuurbes. De
kruidlaag van doornstruwelen is soortenarm, met onder andere Duinriet, Akkerdistel, Grote brandnetel
en Kropaar. Struwelen zijn waardevol voor vogels als de Grauwe klauwier, Grasmus, Braamsluiper,
Geelgors, Roodborsttapuit, Nachtegaal en Bosrietzanger enroofvogels als de Slechtvalk en Torenvalk.
Ze zijn van belang voor tal van insecten waaronder vlindersoorten (Kleine ijsvogelvlinder,
Sleedoornpage) en bieden een schuil- en overwinteringsplaats aan amfibieën (Kamsalamander,
Boomkikker), kleine zoogdieren(Das, Wezel, Hermelijn) en reptielen (Ringslang, Levendbarende
hagedis).


#### Oever \> rivieren \> Oeverwal of uiterwaard vegetatie met lage bedekking (5 - 25%) {#sec-Oeverwal-of-uiterwaard-vegetatie-met-lage-bedekking-5-25-}

### Oever \> rivieren \> OVerstromingsvrij 
Deze zone vormt de bovengrens van de hydrodynamische gradiënt van alle rijkswateren. Navolgende
beschrijving is dan ook van toepassing op alle watersystemen. Getracht is de variatie die er mogelijk nog
is tussen watersystemen enigszins te beschrijven, zonder compleet te kunnen en willen zijn.

Als gevolg van het gevoerde beheer kunnen op grond van de vegetatiestructuur vijf ecotoopgroepen
onderscheiden worden die uiteindelijk leiden tot tien ecotopen.

_Tabel 7: Overzicht ecotopen van de overstromingsvrije zone_

```
Zone Ecotoopgroep Ecotoop Code H M B
Overstromingsvrije antropogeen (A) overstromingsvrije akker HA-1 2rgs G I
zone overstromingsvrij bebouwd HA-2 2 rgs G K
(H) grasland (G) overstromingsvrij natuurlijk grasland HG-1 2 rgs G N/E
overstromingsvrij productiegrasland HG-2 2 rgs G I
ruigte (R) overstromingsvrije ruigte HR-1 2 rgs G N/E
moeras (M) overstromingsvrij riet HM-1 2 rgs G E
overstromingsvrije helofytencultuur HM-2 2 rgs G I
bos (B) overstromingsvrij natuurlijk bos HB-1 2 rgs G N/E
overstromingsvrij struweel HB-2 2 rgs G N/ E
overstromingsvrij productiebos HB-3 2 rgs G I
```
_H = hydrologie: 1 = periodiek tot zelden overstroomd, 2 = overstromingsvrij (de r staat voor rivieren, g voor
getijdenwateren en s voor meren en kanalen)
M = mechanische dynamiek: S = sterk dynamisch,M = matig dynamisch, G = gering dynamisch
B = gebruik/beheer: I = intensief, E = extensief, N = nauwelijks tot geen beheer; K = kunstmatig hard substraat_
(zie tevens tabellen 2, 3 en 4)

#### Oever \> rivieren \> Overstromingsvrij bebouwd {#sec-Overstromingsvrij-bebouwd}

HA-2 Overstromingsvrij bebouwd
Dit ecotoop omvat bebouwde en verharde (b.v. bedrijfsterrein, parkeerterrein, wegen) terreinen.
Binnen dit ecotoop kunnen verschillende ruigte- en pionierbegroeiingen worden aangetroffen. De
ecologische betekenis en samenstelling kunnen sterk per locatie verschillen, afhankelijk van de lokale
bebouwing, het type verharding ende intensiteit waarmee het terrein wordt gebruikt. Veelal kan deze
gezien worden als een afgeleide van de uiterwaardruigte.

#### Oever \> rivieren \> Overstromingsvrij grasland (natuurlijk of productie) {#sec-Overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> rivieren \> Overstromingsvrij hardhoutooibos {#sec-Overstromingsvrij-hardhoutooibos}

#### Oever \> rivieren \> Overstromingsvrij natuurlijk bos {#sec-Overstromingsvrij-natuurlijk-bos}
HB-1 Overstromingsvrij natuurlijk bos

Dit ecotoop omvat bossen buiten de directe invloed van overstromingen met een natuurlijke
bosstructuur bestaande uit een kruidlaag, struiklaag en veelal twee boomlagen (nagenoeg natuurlijke
tot half natuurlijke gebruiksdynamiek).
De soortensamenstelling kan sterk variëren, onder andere afhankelijk van regio, bodemtype, beheer en
leeftijd. Dit bostype is sterk verwant aan het hardhoutooibos, maar is vaak soortenrijker, met name in
de ondergroei. De belangrijkste voorkomende soorten van de boomlaag zijn Es, Zomereik, Gladde iep,
Winterlinde, Spaanse aak, Gewone esdoorn, Zwarte populier en Witte abeel. In de struiklaag zijn onder
andere Eenstijlige meidoorn, Sleedoorn en Hazelaar te vinden,naast klim- en slingerplanten als Hop,
Bosrank, Besanjelier en Warkruid. De kruidlaag is rijk aan geofyten (bol- en knolplanten) als Daslook,
Bosanemoon, Aronskelk, Slanke sleutelbloem en Bosgeelster. In de zomer wordt de kruidlaag
gedomineerd door nitrofiele ruigtesoorten als Grote brandnetel, Dauwbraam, Hondsdraf en Kleefkruid.
Voor vogels als de zwarte Wouw, de Wespendief en de Zwarte ooivaar vormen de hoogwatervrije
bossen een geschikt biotoop. Blauwe reiger, Kwak, Kleine en Middelste bonte specht, Appelvink,
Boomklever en Zomertortel vinden er een broed- en rustgebied. Veel (kleine) zoogdieren, amfibieën en
(bodem)insecten voelen zich hier thuis, onder andere Ree, Das, Rosse vleermuis en de Ruige
dwergvleermuis. Ook de landgoedbossen vallen onder ecotoop, met haartypische stinzevegetatie.

#### Oever \> rivieren \> Overstromingsvrij natuurlijk grasland {#sec-Overstromingsvrij-natuurlijk-grasland}

HG-1 Overstromingsvrij natuurlijk grasland

In tegenstelling tot deproductiegraslanden kent dit ecotoop (indien sprake is van begrazing) een
extensieve vorm van begrazingsbeheer en dientengevolge een geringere mestgift.

Het ecotoop omvat alle typische vormen van glanshaverhooilanden en kamgrasweiden. Voorbeelden
van voorkomende plantensoorten in kamgrasweiden zijn Brede, Liggende en Vroege ereprijs, Veldsalie,
Kluwenklokje, Kamgras, Knopig doornzaad, Veldgerst. Begeleidende soorten van glanshaverhooilanden
zijn: Goudhaver, Roodzwenkgras, Gele morgenster, Groot streepzaad,Glad walstro en Gewone
hoornbloem. Meer bijzondere soorten zijn de Gewone agrimonie, Karwijselie en Oosterse morgenster
De bloemrijke vegetaties zijn vaak rijk aan insecten. De Veldparelmoervlinder is één van de vele
vlindersoorten die zich hier voortplant. De soortenrijke vegetaties zijn van belang voor grondbroedende
vogelsoorten als Patrijs, Grutto, Kievit, Tureluur, Goudplevier, Veldleeuwerik, Gele kwikstaart en
Kwartelkoning. Bij een behoorlijke omvang kan het ecotoop een belangrijke functie hebben als
foerageergebied voor ganzen en zwanen. Het is een geliefd biotoop voor kleine zoogdieren, zoals de
Rosse vleermuis en de Das.

#### Oever \> rivieren \> Overstromingsvrij onbegroeid (antropogeen) {#sec-Overstromingsvrij-onbegroeid-antropogeen-}

#### Oever \> rivieren \> Overstromingsvrij productiebos {#sec-Overstromingsvrij-productiebos}

HB-3 Overstromingsvrij productiebos

Dit ecotoop wordt beheerd tenbehoeve van de houtproductie; de boomlaag is in het algemeen
éénsoortig. Veel voorkomende productiesoorten zijn Gewone es, Grove den en Zomereik. In meer
vochtige omstandigheden kunnen populieren en wilgen aangeplant worden. In dat geval ontstaan er
ruigten met nitrofiele soorten als Dauwbraam en Grote brandnetel. Een bijzondere vorm zijn de
grienden, bestaande uit (knot)wilgen. Met hun dichte, ruige ondergroei trekken ze hoge aantallen
kleine zoogdieren (muizen) en bodemfauna (spinnen) aan en vormen een geschikt broedhabitat voor
water- en bosvogels. De kruid- en struiklaag van de overige productiebostypen zijn relatief soort- en
structuurarm. Hakhoutbossen (es of eik) worden ook tot het ecotoop productiebos gerekend, evenals
boomgaarden en laanbomen.

#### Oever \> rivieren \> Overstromingsvrij productiegrasland {#sec-Overstromingsvrij-productiegrasland}

HG-2 Overstromingsvrij productiegrasland

Het ecotoop productiegrasland staat onder intense agrarische druk en de bemestingsgraad is hoog.
Over het algemeen zijn het structuur- en soortenarme graslanden. De vegetatie wordt gedomineerd
door ingezaaide grassoorten zoals Engels raaigras en kent een beperkt aantal kruidachtige soorten.
Indien de mestgift matig is, kan een intensief bodemleven ontstaan, vol wormen en insecten die dienen
als voedsel voor vogels. In dat geval kunnen de graslanden een grote betekenis hebben als foerageer-
en broedgebied voor weidevogels. Bij een behoorlijke omvang heeft het ecotoop een belangrijke functie
als foerageergebied voor overwinteraars als ganzen (Rotgans, Kolgans, Brandgans en Grauwe gans),
zwanen (Kleine zwaan en Knobbelzwaan) en de Goudplevier.
Golfbanen en recreatieterreinen worden ook tot deze ecotoopgroep gerekend.

#### Oever \> rivieren \> Overstromingsvrij riet {#sec-Overstromingsvrij-riet}

HM-1 Overstromingsvrij riet

Het ecotoop wordt gedomineerd door overjarig riet. Hierin komen in lage bedekking ook ruigtekruiden
en graslandsoorten voor, zoals Harig wilgeroosje, Akkerdistel, Heen en Fioringras. In het hooggelegen
rietland kunnen de (minder kieskeurige) kenmerkende vogelsoorten van het rietmoeras voorkomen,
zoals Kleine karekiet, Rietzanger, Rietgors, Blauwborst, Bosrietzanger en Bruine kiekendief. Dit ecotoop
gaat zonder beheer over in moerasstruweel/-bos, met wilg, els en braamstruiken.

HM-2 Overstromingsvrije helofytencultuur

Het ecotoop komt tot stand onder agrarisch gebruik of onder maaibeheer ten behoeve van
natuurbeschermingsdoelstellingen. Riet en Mattenbies domineren de vegetatie. Wanneer de verstoring
niet zeer groot is (het maaibeheer vindt plaats in het najaar en er wordt maximaal één keer per jaar
gemaaid), heeft het ecotoop betekenis als broed- en foerageergebied voor weidevogels en watervogels,
onder andere Rietgors, Blauwborst en Kleine karekiet. In het zoetwatergetijdegebied kunnen soorten als
Spindotterbloem, Bittere veldkers, Witte waterkers, Rode Waterereprijs en Heen aangetroffen worden.
#### Oever \> rivieren \> Overstromingsvrij struweel {#sec-Overstromingsvrij-struweel}

HB-2 Overstromingsvrij struweel

De overstromingsvrije doornstruwelen bestaan uit soorten uit de struiklaag van het hardhoutooibos:
Eenstijlige meidoorn, Sleedoorn, Kardinaalsmuts, Gewone vlier, Lijsterbes, Hondsroosen Dauwbraam.
In het overgangsgebied met het water van de zoute Delta komen duinstruwelen voor met struiksoorten
als Duindoorn, Wegedoorn, Wilde liguster en Zuurbes. De kruidlaag van struwelen is soortenarm, met
onder andere Duinriet, Akkerdistel, Grote brandnetel en Kropaar. Struwelen zijn waardevol voor vogels
als de Grauwe klauwier, Grasmus, Braamsluiper, Geelgors, Roodborsttapuit, Nachtegaal en
Bosrietzanger en roofvogels als de Slechtvalk en Torenvalk. Ze zijn van belang voor tal van insecten
waarondervlindersoorten (Kleine ijsvogelvlinder, Sleedoornpage) en bieden een schuil- en
overwinteringsplaats aan amfibieën (Kamsalamander, Boomkikker), kleine zoogdieren (Das, Wezel,
Hermelijn) en reptielen (Ringslang, Levendbarende hagedis).
Op nattere locaties, waar bijvoorbeeld regenwater stagneert, vormen zich zachthoutstruwelen met
wilgenopslag. Hier zijn de struikwilgen Amandelwilg, Bittere wilg, Grauwe wilg en Katwilg te vinden,


vaak ook jonge Schietwilgen en soms Zwarte populieren. De kruidlaag bestaat uit pionierkruiden als
Gele waterkers en soorten als Grote brandnetel en Scherpe zegge. Kleine zangvogels vinden hier een
foerageer- en broedplek, bijvoorbeeld de Buidelmees en de Tjiftjaf.

#### Oever \> rivieren \> Overstromingsvrije akker {#sec-Overstromingsvrije-akker}

HA-1 Overstromingsvrije akker

Tot dit ecotoop worden alle bouwlanden, zowel kaal als begroeid, in de overstromingsvrije zone. Ook
volle grond kwekerijen (zoals rozen en bessen), die onder andere langs de onbedijkte Maas worden
aangetroffen worden tot dit ecotoop gerekend. Akkers worden gekenmerkt door een hoge
gebruiksdynamiek (intensief beheer) en worden vaak (zwaar) bemest.
De ecologische betekenis van deze akkers is in grote mate afhankelijk van het gevoerde
landbouwkundig beheer. De soortensamenstelling van de vegetatie is veelal zeer beperkt, en is te
beschouwen als een verarmde variant van de overstromingsvrije ruigte. Afhankelijk van het beheer kan
een aantal karakteristieke soorten voorkomen. Bij een relatief extensief beheer, waarbij ruimte is voor
overstaande randvegetaties en verlaten hoekjes kunnen de Gele kwikstaart, Veldleeuwerik, Patrijs en
Kwartelkoning in lage aantallen aangetroffen worden.

#### Oever \> rivieren \> Overstromingsvrije hoogstamboomgaard {#sec-Overstromingsvrije-hoogstamboomgaard}

#### Oever \> rivieren \> Overstromingsvrije laagstamboomgaard {#sec-Overstromingsvrije-laagstamboomgaard}

#### Oever \> rivieren \> Overstromingsvrije ruigte {#sec-Overstromingsvrije-ruigte}

HR-1 Overstromingsvrije ruigte

Overstromingsvrije ruigtes kunnen zowel structuurarm als structuurrijk zijn, afhankelijk van de intensiteit
van het beheer. De soortenrijke variant bestaat uit twee- en meerjarige ruigtekruiden, die al dan niet
afhankelijk zijn van grondwater. Voorbeelden van voorkomende plantensoorten zijn Poelruit, Gewone
wederik, Grote valeriaan, Akkerdistel, Boeren wormkruid, Harig wilgeroosje, Moeraskruiskruid en in
nattere omstandigheden ook het Rivierkruiskruid.
Op meer verrijkte bodems ontstaan soort- en structuurarmere vegetaties. De soort- en structuurrijkdom
neemt vaak ook af ten gevolge van voortschrijdende successie.Voorbeelden van dominerende soorten
zijnGrote brandnetel, Ridderzuring, Dauwbraam, Smalbladige asters en ruige grassen als Rietgras,
Kweek en Kropaar. De ruigten fungeren als broedgelegenheid voor soorten als Blauwborst,
Bosrietzanger, Roodborst tapuit, Grasmus, Rietgors, Sprinkhaanrietzanger en Kwartelkoning. Het is
tevens een belangrijk ecotoop voor zoogdieren en insecten.

#### Oever \> rivieren \> Overstromingsvrije vegetatie met lage bedekking (5 - 25%) {#sec-Overstromingsvrije-vegetatie-met-lage-bedekking-5-25-}

### Oever \> getijdewateren {#sec-getijdewateren}

#### Oever \> getijdewateren \> Akker in oever {#sec-Akker-in-oever}

#### Oever \> getijdewateren \> Brakke helofytencultuur {#sec-Brakke-helofytencultuur}

#### Oever \> getijdewateren \> Grasland in oever {#sec-Grasland-in-oever}

#### Oever \> getijdewateren \> Griend in oever {#sec-Griend-in-oever}

#### Oever \> getijdewateren \> Hard substraat in laag littoraal zout getijdenwater {#sec-Hard-substraat-in-laag-littoraal-zout-getijdenwater}

#### Oever \> getijdewateren \> Helofytenmoeras (riet/moerasplanten) in oever {#sec-Helofytenmoeras-riet-moerasplanten-in-oever}

#### Oever \> getijdewateren \> Hoogstamboomgaard in oever {#sec-Hoogstamboomgaard-in-oever}

#### Oever \> getijdewateren \> Laagstamboomgaard in oever {#sec-Laagstamboomgaard-in-oever}

#### Oever \> getijdewateren \> Matig dynamisch brak tot zout ondiep water/brak biezengors {#sec-Matig-dynamisch-brak-tot-zout-ondiep-water-brak-biezengors}

#### Oever \> getijdewateren \> Matig dynamisch hard substraat op de buitenberm onder invloed van getijdenwater {#sec-Matig-dynamisch-hard-substraat-op-de-buitenberm-onder-invloed-van-getijdenwater}

#### Oever \> getijdewateren \> Matig dynamisch zoet tot zwak brak ondiep water/zoetwater biezengors {#sec-Matig-dynamisch-zoet-tot-zwak-brak-ondiep-water-zoetwater-biezengors}

#### Oever \> getijdewateren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water}

#### Oever \> getijdewateren \> Moerasruigte in oever {#sec-Moerasruigte-in-oever}

#### Oever \> getijdewateren \> Moerasruigte/gorsruigte in oever {#sec-Moerasruigte-gorsruigte-in-oever}

#### Oever \> getijdewateren \> Moerassig overstromingsgrasland in oever {#sec-Moerassig-overstromingsgrasland-in-oever}

#### Oever \> getijdewateren \> Moerassig overstromingsgrasland/productiegrasland in oever {#sec-Moerassig-overstromingsgrasland-productiegrasland-in-oever}

#### Oever \> getijdewateren \> Moerassig structuurrijk overstromingsgrasland {#sec-Moerassig-structuurrijk-overstromingsgrasland}

#### Oever \> getijdewateren \> Onbegroeid (antropogeen) in oever {#sec-Onbegroeid-antropogeen-in-oever}

#### Oever \> getijdewateren \> Overstromingsarm vloedbos {#sec-Overstromingsarm-vloedbos}

#### Oever \> getijdewateren \> Productiebos in oever {#sec-Productiebos-in-oever}

#### Oever \> getijdewateren \> Productiegrasland in oever {#sec-Productiegrasland-in-oever}

#### Oever \> getijdewateren \> Soortenarm helofytenmoeras van het supralittoraal {#sec-Soortenarm-helofytenmoeras-van-het-supralittoraal}

#### Oever \> getijdewateren \> Soortenarme helofytenvegetatie in ondiep water {#sec-Soortenarme-helofytenvegetatie-in-ondiep-water}

#### Oever \> getijdewateren \> Sterk dynamische brakke en zoute zandige platen/matig dynamische brakke en zoute lage platen {#sec-Sterk-dynamische-brakke-en-zoute-zandige-platen-matig-dynamische-brakke-en-zoute-lage-platen}

#### Oever \> getijdewateren \> Tijdelijk kaal {#sec-Tijdelijk-kaal}

#### Oever \> getijdewateren \> Vegetatie met lage bedekking (5 - 25%) in oever {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever}

#### Oever \> getijdewateren \> Vloedbos in oever {#sec-Vloedbos-in-oever}

#### Oever \> getijdewateren \> Zachthout ooibos in oever {#sec-Zachthout-ooibos-in-oever}

#### Oever \> getijdewateren \> Zachthout struweel {#sec-Zachthout-struweel}

#### Oever \> getijdewateren \> Zachthout struweel in oever {#sec-Zachthout-struweel-in-oever}

#### Oever \> getijdewateren \> Zoete zandplaten/zoete slibrijke platen {#sec-Zoete-zandplaten-zoete-slibrijke-platen}

#### Oever \> getijdewateren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water/overstromingsvrij bebouwd {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water-overstromingsvrij-bebouwd}

#### Oever \> getijdewateren \> Moerasruigte/gorsruigte/overstromingsvrije ruigte {#sec-Moerasruigte-gorsruigte-overstromingsvrije-ruigte}

#### Oever \> getijdewateren \> Oever of overstromingsvrij grasland (natuurlijk of productie) {#sec-Oever-of-overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> getijdewateren \> Oever of overstromingsvrij natuurlijk bos {#sec-Oever-of-overstromingsvrij-natuurlijk-bos}

#### Oever \> getijdewateren \> Oever of overstromingsvrij natuurlijk grasland {#sec-Oever-of-overstromingsvrij-natuurlijk-grasland}

#### Oever \> getijdewateren \> Oever of overstromingsvrij productiebos {#sec-Oever-of-overstromingsvrij-productiebos}

#### Oever \> getijdewateren \> Oever of overstromingsvrij productiegrasland {#sec-Oever-of-overstromingsvrij-productiegrasland}

#### Oever \> getijdewateren \> Oever of overstromingsvrij struweel {#sec-Oever-of-overstromingsvrij-struweel}

#### Oever \> getijdewateren \> Soortenarme moerasruigte/overstromingsvrij riet {#sec-Soortenarme-moerasruigte-overstromingsvrij-riet}

#### Oever \> getijdewateren \> Vegetatie met lage bedekking (5 - 25%) in oever of overstromingsvrij {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever-of-overstromingsvrij}

#### Oever \> getijdewateren \> Overstromingsvrij bebouwd {#sec-Overstromingsvrij-bebouwd}

#### Oever \> getijdewateren \> Overstromingsvrij grasland (natuurlijk of productie) {#sec-Overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> getijdewateren \> Overstromingsvrij natuurlijk bos {#sec-Overstromingsvrij-natuurlijk-bos}

#### Oever \> getijdewateren \> Overstromingsvrij natuurlijk grasland {#sec-Overstromingsvrij-natuurlijk-grasland}

#### Oever \> getijdewateren \> Overstromingsvrij onbegroeid (antropogeen) {#sec-Overstromingsvrij-onbegroeid-antropogeen-}

#### Oever \> getijdewateren \> Overstromingsvrij productiebos {#sec-Overstromingsvrij-productiebos}

#### Oever \> getijdewateren \> Overstromingsvrij productiegrasland {#sec-Overstromingsvrij-productiegrasland}

#### Oever \> getijdewateren \> Overstromingsvrij riet {#sec-Overstromingsvrij-riet}

#### Oever \> getijdewateren \> Overstromingsvrij struweel {#sec-Overstromingsvrij-struweel}

#### Oever \> getijdewateren \> Overstromingsvrij tijdelijk kaal {#sec-Overstromingsvrij-tijdelijk-kaal}

#### Oever \> getijdewateren \> Overstromingsvrije akker {#sec-Overstromingsvrije-akker}

#### Oever \> getijdewateren \> Overstromingsvrije hoogstamboomgaard {#sec-Overstromingsvrije-hoogstamboomgaard}

#### Oever \> getijdewateren \> Overstromingsvrije laagstamboomgaard {#sec-Overstromingsvrije-laagstamboomgaard}

#### Oever \> getijdewateren \> Overstromingsvrije ruigte {#sec-Overstromingsvrije-ruigte}

#### Oever \> getijdewateren \> Overstromingsvrije vegetatie met lage bedekking (5 - 25%) {#sec-Overstromingsvrije-vegetatie-met-lage-bedekking-5-25-}

### Oever \> meren {#sec-meren}

#### Oever \> meren \> Akker in oever {#sec-Akker-in-oever}

#### Oever \> meren \> Dynamisch zoet tot zwak brak ondiep water {#sec-Dynamisch-zoet-tot-zwak-brak-ondiep-water}

#### Oever \> meren \> Gering dynamisch zoet tot zwak brak ondiep water {#sec-Gering-dynamisch-zoet-tot-zwak-brak-ondiep-water}

#### Oever \> meren \> Grasland in oever {#sec-Grasland-in-oever}

#### Oever \> meren \> Hard substraat in laag littoraal zout getijdenwater {#sec-Hard-substraat-in-laag-littoraal-zout-getijdenwater}

#### Oever \> meren \> Helofytenmoeras (riet/moerasplanten) in oever {#sec-Helofytenmoeras-riet-moerasplanten-in-oever}

#### Oever \> meren \> Hoogstamboomgaard in oever {#sec-Hoogstamboomgaard-in-oever}

#### Oever \> meren \> Laagstamboomgaard in oever {#sec-Laagstamboomgaard-in-oever}

#### Oever \> meren \> Matig dynamisch hard substraat op de buitenberm onder invloed van getijdenwater {#sec-Matig-dynamisch-hard-substraat-op-de-buitenberm-onder-invloed-van-getijdenwater}

#### Oever \> meren \> Matig dynamisch zoet tot zwak brak ondiep water {#sec-Matig-dynamisch-zoet-tot-zwak-brak-ondiep-water}

#### Oever \> meren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water}

#### Oever \> meren \> Moerasplanten en helofytenzone {#sec-Moerasplanten-en-helofytenzone}

#### Oever \> meren \> Moerasruigte in oever {#sec-Moerasruigte-in-oever}

#### Oever \> meren \> Moerasruigte/gorsruigte in oever {#sec-Moerasruigte-gorsruigte-in-oever}

#### Oever \> meren \> Moerassig overstromingsgrasland in oever {#sec-Moerassig-overstromingsgrasland-in-oever}

#### Oever \> meren \> Moerassig overstromingsgrasland/productiegrasland in oever {#sec-Moerassig-overstromingsgrasland-productiegrasland-in-oever}

#### Oever \> meren \> Moerassig structuurrijk overstromingsgrasland {#sec-Moerassig-structuurrijk-overstromingsgrasland}

#### Oever \> meren \> Onbegroeid (antropogeen) in oever {#sec-Onbegroeid-antropogeen-in-oever}

#### Oever \> meren \> Productiebos in oever {#sec-Productiebos-in-oever}

#### Oever \> meren \> Productiegrasland in oever {#sec-Productiegrasland-in-oever}

#### Oever \> meren \> Soortenarme helofytenvegetatie in ondiep water {#sec-Soortenarme-helofytenvegetatie-in-ondiep-water}

#### Oever \> meren \> Vegetatie met lage bedekking (5 - 25%) in oever {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever}

#### Oever \> meren \> Zachthout ooibos in oever {#sec-Zachthout-ooibos-in-oever}

#### Oever \> meren \> Zachthout struweel in oever {#sec-Zachthout-struweel-in-oever}

#### Oever \> meren \> Zoete zandplaten {#sec-Zoete-zandplaten}

#### Oever \> meren \> Zoetwater biezengors {#sec-Zoetwater-biezengors}

#### Oever \> meren \> Matig tot sterk dynamisch hard substraat onder invloed van zoet of brak water/overstromingsvrij bebouwd {#sec-Matig-tot-sterk-dynamisch-hard-substraat-onder-invloed-van-zoet-of-brak-water-overstromingsvrij-bebouwd}

#### Oever \> meren \> Moerasruigte/gorsruigte/overstromingsvrije ruigte {#sec-Moerasruigte-gorsruigte-overstromingsvrije-ruigte}

#### Oever \> meren \> Oever of overstromingsvrij grasland (natuurlijk of productie) {#sec-Oever-of-overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> meren \> Oever of overstromingsvrij natuurlijk bos {#sec-Oever-of-overstromingsvrij-natuurlijk-bos}

#### Oever \> meren \> Oever of overstromingsvrij natuurlijk grasland {#sec-Oever-of-overstromingsvrij-natuurlijk-grasland}

#### Oever \> meren \> Oever of overstromingsvrij productiebos {#sec-Oever-of-overstromingsvrij-productiebos}

#### Oever \> meren \> Oever of overstromingsvrij productiegrasland {#sec-Oever-of-overstromingsvrij-productiegrasland}

#### Oever \> meren \> Oever of overstromingsvrij struweel {#sec-Oever-of-overstromingsvrij-struweel}

#### Oever \> meren \> Vegetatie met lage bedekking (5 - 25%) in oever of overstromingsvrij {#sec-Vegetatie-met-lage-bedekking-5-25-in-oever-of-overstromingsvrij}

#### Oever \> meren \> Overstromingsvrij bebouwd {#sec-Overstromingsvrij-bebouwd}

#### Oever \> meren \> Overstromingsvrij grasland (natuurlijk of productie) {#sec-Overstromingsvrij-grasland-natuurlijk-of-productie-}

#### Oever \> meren \> Overstromingsvrij natuurlijk bos {#sec-Overstromingsvrij-natuurlijk-bos}

#### Oever \> meren \> Overstromingsvrij natuurlijk grasland {#sec-Overstromingsvrij-natuurlijk-grasland}

#### Oever \> meren \> Overstromingsvrij onbegroeid (antropogeen) {#sec-Overstromingsvrij-onbegroeid-antropogeen-}

#### Oever \> meren \> Overstromingsvrij productiebos {#sec-Overstromingsvrij-productiebos}

#### Oever \> meren \> Overstromingsvrij productiegrasland {#sec-Overstromingsvrij-productiegrasland}

#### Oever \> meren \> Overstromingsvrij riet {#sec-Overstromingsvrij-riet}

#### Oever \> meren \> Overstromingsvrij struweel {#sec-Overstromingsvrij-struweel}

#### Oever \> meren \> Overstromingsvrije akker {#sec-Overstromingsvrije-akker}

#### Oever \> meren \> Overstromingsvrije hoogstamboomgaard {#sec-Overstromingsvrije-hoogstamboomgaard}

#### Oever \> meren \> Overstromingsvrije laagstamboomgaard {#sec-Overstromingsvrije-laagstamboomgaard}

#### Oever \> meren \> Overstromingsvrije ruigte {#sec-Overstromingsvrije-ruigte}

#### Oever \> meren \> Overstromingsvrije vegetatie met lage bedekking (5 - 25%) {#sec-Overstromingsvrije-vegetatie-met-lage-bedekking-5-25-}
