# Indelingskenmerken

> Dit geheel is rechtstreekse kopie van het rapport, dit moet op de een of andere manier duideljk worden. Er moet dan een apart hoofdstuk komen met de recente versie met updates (welke updates er geweest zijn is nog niet precies helder, moet ook blijken uit de vergelijking van de draaitabel met de tabellen en indeling in het rapport, er zijn mogelijk ecotopen bijgekomen.
>
> De indelingskenmerken bovenin de draaitabel zijn klikbaar en verwijzen naar de beschrijving van salitiniteit dynamiek, etc.
>
> De draaitabel zelf staat in een ander hoofdstuk waarin je per systeem de ecotopen ziet
>
> ELke Ecotoop in de draaitabel is ook aanklikbaar en verwijst naar een beschrijving van het ecotoop met soorten.
>
> Elk systeem wordt ook apart beschreven

## Inleiding {#sec-inleiding-indeling}

Voor de structuur van dit aanvullend ecotopenstelsel wordt in aansluiting op de structuur van de bestaande Rijkswateren-Ecotopen-Stelsels een hierarchische indeling gevolgd (figuur 3). De hierarchie biedt de mogelijkheid om zowel de verschillende watersystemen als de verschillende ecotopen, en de daarbij onderscheiden eco-elementen, op een overzichtelijke wijze in een stelsel onder te brengen. Het gaat hier om een ruimtelijke hierarchie: groepen van watersystemen worden gekenmerkt door specifieke combinaties van ecotopen, die voorkomen in zich herhalende ruimtelijke patronen. Op verschillende niveau's worden verschillende indelingskenmerken gehanteerd. Deze indelingskenmerken worden opgedeeld in klassen op basis van ecologisch bepaalde grenzen. Op het laagste niveau worden eco-elementen onderscheiden op basis van het voorkomen van een bepaalde soort(groep). De Nederlandse rijkswateren zijn ingedeeld in watersystemen op basis van de positionele factoren stromingsrichting en saliniteit, zie paragraaf @sec-stromingsrichting en @sec-saliniteit. Ecotopen worden onderscheiden op basis van conditionele factoren, waarbij het zoutgehalte echter zorgt voor een verdere onderverdeling binnen de getijdenwateren en de kanalen. In paragraaf @sec-mechanische-dynamiek @sec wordt het dynamisch karakter uitgewerkt, in paragraaf @sec-waterdiepte de waterdiepte en in paragraaf @sec-bodemtype het bodemtype. In paragraaf @sec- 3.7 wordt ingegaan op het onderscheiden van eco-elementen op basis van de aanwezigheid van soort(groep)en.

## Stromingsrichting  {#sec-stromingsrichting}

Dit indelingskenmerk is van toepassing op het systeem AQUATISCH en OEVERS

Het verhang in een systeem bepaalt de richting en snelheid waarmee het water zich beweegt. Bij getijdenwateren is ook de invloed van het getijde van belang voor de beweging van het water; de stromingsrichting kan zelfs tijdelijk worden omgekeerd door invloed van hoogwater. De stromingsrichting wordt ingedeeld in drie klassen: eenzijdige stroming, tweezijdige stroming en geen stroming (geTsoleerde wateren). Op basis van deze klassen worden de Nederlandse rijkswateren ingedeeld in respectievelijk rivieren, getijdenwateren en meren en kanalen.

HIER VERWIJZEN NAAR RIVIEREN, GETIJDENWATER, MEREN en KANALEN

Een stromingsrichting en jaarlijkse waterstands-fluctuaties bepalen de hydrodynamiek en morfodynamiek voor riviersystemen. In de getijdenwateren treden door de getijdenwerking in het algemeen per etmaal wisselingen in waterstand en stroomrichting op. In de meren en kanalen is de invloed van stroming en waterstandsfluctuaties veel kleiner. Zoals aangegeven in paragraaf 2.3 worden meren en kanalen onderscheiden op basis van hun vorm en de openheid.

De grens tussen rivieren en getijdenwateren is gekozen op basis van het al of niet voorkomen van voor getijdenwateren specifieke ecotopen, te weten biezen- en rietgorzen. De situatie van de Merwede/Waal is hierbij het uitgangspunt, omdat dit een vrij afstromende rivier is. Deze grens ligt bij een getijverschil (onder gemiddelde omstandigheden) tussen hoog- en laagwater van circa 30 centimeter. Deze grens valt bovendien samen met de meest stroomopwaarts gelegen locaties van ongerijpte kleigronden (gors-vaaggronden) en met een knik in de verhanglijn van de top van de holocene afzetting (Maas, 1998).

## Saliniteit {#sec-saliniteit}

Dit indelingskenmerk is van toepassing op het systeem AQUATISCH en OEVERS

In deze studie is het zoutgehalte (saliniteit) de onderscheidende factor tussen zoete, brakke en zoute watersystemen. Zoet eindigt vaak bij een zoutgehalte van 0,3 g Cl /I (tabel 1). Stijgt het zoutgehalte van het water boven dit niveau uit, dan verdwijnen zoetwatersoorten uit het systeem en ver-schijnen zogenaamde brakwatersoorten (figuur 5). Naast het zoutgehalte zijn de concentratie zuurstof, de temperatuur en de troebelheid van het water sleutelfactoren voor de ecologische ontwikkelingsmogelijkheden in de overgangszone tussen zoet en zout. Daarnaast is er een veelheid aan gradienten die op een of andere manier de biota kunnen beinvloeden. Voorbeelden hiervan zijn nutrienten (bijvoorbeeld P04, N03, NO,, POC. Si), redox, metalen en organische verontreinigingen, grootte van sediment-deeltjes, golfwerking en bioturbatie (McLusky. 1993). Deze en andere gradienten, die bovendien vaak covarieren, zijn van secundair belang in vergelijking tot de sleutelfactoren.

> Saliniteit en chloriniteit
>
> Saliniteit drukt het gehalte aan opgeloste ionen uit. Omdat de verhouding tussen de ionen redelijk constant is, wordt vaak gebruik gemaakt van het chloridegehalte (chloriniteit). Dit ion is relatief eenvoudig te meten. Het chloridegehalte maal 1,8066 levert de totale saliniteit.

De invloed van zout op het ecologisch functioneren bestaat uit verschillende componenten. In de lengterichting van een natuurlijk riviersysteem is er een toename van het zoutgehalte in de richting van zee. Zeewater (circa 18 g CI7I) mengt zich met zoet rivierwater (\< 0,3 g CM) en hierdoor ontstaat een in zeewaartse richting oplopende saliniteitsgradient. Doordat de rivierafvoer en de hoogte van het getij in sterkte kunnen fluctueren, kan de saliniteitsgradient periodiek in zee- of landinwaartse richting verschuiven. Lage rivierafvoeren en een verhoogde waterstand bevorderen het indringen van zout water stroomopwaarts. Cadee (1994) heeft op basis van het estuariumgetal (N = de verhouding tussen zee- en rivierinvloed in een estuarium oftewel de rivierafvoer per getijcyclus (gemiddeld 12,5 uur) gedeeld door het getijvolume) een scheiding gemaakt tussen enkele Europese estuaria met een relatief grote rivierinvloed (N: 2,5 - 7,7%), te weten Elbe, Gironde, Ythan en Loire, en estuaria met een geringe rivierinvloed (N: 0,25 - 0,4%), te weten Schelde, Humber en Eems. De waarde van N geeft een goede indicatie voor het verloop van de saliniteitsgradient en de als gevolg daarvan optredende ecologische ontwikkelingen. Van de huidige en voormalige Nederlandse estuaria had alleen het Haringvliet een hoog estuarium getal (Eertman & Smaal, 1997). Bij de beschrijving van eventuele ecologische referenties dient hiermee zeker rekening gehouden te worden. Niet alleen de zoutconcentratie maar ook de zoutsamenstelling van het water kan op een bepaalde locatie gedurende het jaar erg wisselen. Hiermee wordt verder geen rekening gehouden. Naast de longitudinale zoutgradient is er een verticale zoutgradient in de aquatische milieus. Als gevolg van een hoger soortelijk gewicht van zout ten opzichte van zoet water ontstaat er een gelaagdheid in het zoutgehalte van het water. De laag net boven de bodem heeft vaak een hoger zoutgehalte in vergelijking met de waterlagen daarboven (zouttong). Een adequate menging van zoet en zout water is onder meer afhankelijk van de grootte van de rivierafvoer in verhouding tot de getijinvloed en de vorm van het estuarium. Tenslotte is voor de oeverzone en de terrestrische delen nog een laterale component van belang, die samenhangt met overspoelingsfrequentie en -duur. Naarmate een standplaats minder vaak met zout water wordt overspoeld. neemt de invloed van regenwater toe en daarmee het zoutgehalte af. Dit betekent dat in het overgangstraject van zoet naar zout, evenals bij de overgang van rivier- naar zoete getijdenwateren, systeemspecifieke ecotopen uit verschillende watersystemen naast elkaar kunnen voorkomen. Aangezien het moeilijk is de verticale- en laterale zoutgradient te kwantificeren en ruimtelijk weer te geven, is de indeling naar zoutgehalte gebaseerd op de longitudinale zoutgradient, uitgaande van volledige menging. Op basis van de longitudinale zoutgradient verdeelde McLusky (1993) een natuurlijk estuarium in een vijftal kenmerkende zones (tabel 1). In grote lijn komen deze zones ook overeen met de indeling van wateren volgens het bekende Venetie-systeem (1958) en de ecologische indeling van Remane (1934) en den Hartog (1959; 1971). Het spreekt voor zich dat, afhankelijk van het type estuarium, een zone een groter of kleiner areaal in beslag kan nemen. De zones volgen elkaar altijd in de hier onder beschreven volgorde op:

-   Zoetwatergetijdenzone. Het meest stroomafwaarts gelegen deel van de rivier, waar de getijdeninvloed merkbaar is (tot 30 cm getijverschil). Er is geen zoutindringing vanuit zee in deze zone. De saliniteit is lager dan 0,3 g CM. Deze zone wordt gekenmerkt door zoetwatersoorten die getijtolerant zijn.

-   Oligohaliene of zwak brakke zone. De zone waar het zoete rivierwater voor het eerst in contact komt met zeewater. De zone staat onder getijdeninvloed, maar de rivierstroming domineert de dynamiek. De zoutindringing is nog zeer gering. De saliniteit varieert van 0,3 tot 3 g CM. Overigens legt den Hartog (1971) de grens tussen oligohalien en mesohalien reeds bij 1,8 CM. De zone wordt gekenmerkt door zoetwaterorganismen die getij- en zouttolerant zijn en brakwaterorganismen.

-   Mesohaliene of brakke zone. De zone waar rivierwater en getijdestroom elkaar ontmoeten. De saliniteit varieert van 3 tot 10 g CM. Deze zone wordt gekenmerkt door brakwaterorganismen. De stromingen zijn minimaal (zogenaamde stagnante punten), in het bijzonder tijdens vloed, wat resulteert in troebelheidsmaxima. De aanwezigheid en de grootte van de troebelheidsmaxima wordt door een aantal factoren bepaald, zoals de concentratie zwevende stof in het rivier- en zeewater, de circulatie in het estuarium en de sedimentatiesnelheid van het aanwezige zwevende materiaal. In deze zone sedimenteren hoofdzakelijk slibdeeltjes. Bij de troebelheidsmaxima wordt in een estuarium de hoogste concentratie organisch materiaal aangetroffen. De concentratie in het water is doorgaans een factor 2 - 3 lager dan in de rivier en een factor 2 - 4 hoger dan in zee (McLusky, 1989). In vergelijking tot de open zee zijn de estuaria zeer voedselrijk.

-   Polyhaliene of sterk brakke zone. In deze zone nemen de getijstromen toe van zwak tot matig. De sedimentatie van slibdeeltjes gaat bij toenemende stroming over in een sedimentatie van zandige deeltjes. De saliniteit varieert van 10 tot 18 g CM. Deze zone wordt gekenmerkt door brakwatersoorten met een grote zouttolerantie en mariene soorten.

-   Euhaliene, zoute of mariene zone. Deze zone bevindt zich in het mondingsgebied van het estuarium en wordt gekenmerkt door sterke getijstromen. Er vindt alleen sedimentatie van zandige deeltjes plaats. De saliniteit wijkt niet veel af van die van de zee (\> 18 g CM). Deze zone wordt gekenmerkt door mariene soorten.

| Klassen                  | Ecologische beschrijving                                                       | Chloriniteit (g Cl/l) | Code |
|---------------------|------------------------------|---------------|-------|
| Zoet                     | Alleen geschikt voor zoetwater soorten                                         | \< 0,3                | F    |
| Zwak brak (Oligohalien)  | Geschikt voor zoetwaterorganismen die zouttolerant zijn en brakwaterorganismen | 0,3 - 3               | L    |
| Brak (Meschalien)        | Gekenmerkt door brakwaterorganismen                                            | 3 - 10                | B    |
| Zout (Poly- en euhalien) | Gekenmerkt door zoutwaterorganismen                                            | \>10                  | Z    |

: Klassenindeling van het indelingskenmerk zoutgehalte

De getijdenwateren worden in dit rapport onderverdeeld naar zoet, zwak brak en brak. Zoet water heeft als bovengrens 0,3 g CM. Zwak brak ligt in de range van 0,3 tot 3 en brak van 3 tot 10 g CM. Voor kanalen is het onderscheid tussen de verschillende brakke zones niet gemaakt. De indeling is gebaseerd op enerzijds de ecologische verschillen tussen gebieden en anderzijds het werkbaar houden van het stelsel in verband met het aantal ecotopen.

## Mechanische dynamiek {#sec-mechanische-dynamiek}

Mechanische dynamiek omvat alle krachten die worden uitgeoefend op zowel bodem, water, vegetatie als fauna van een ecotoop. Het gaat daarbij om erosie- en sedimentatieprocessen, transport van sediment (grind, zand en klei) en circulatiestromingen. Erosie- en sedimentatieprocessen staan niettemin centraal bij de mechanische dynamiek. In tabel 2 staan de factoren die de mate van dynamiek in verschillende hoofdwatersystemen van de Nederlandse rijkswateren bepalen, zoals die ook staan aangegeven in het RES, BES, MES en KES. De mechanische dynamiek wordt onderscheiden in vier verschillende klassen, waarbij de grenzen zijn gebaseerd op de kansen voor vestiging van vegetatie en/of bodemfauna (tabel 3).

TABEL 2

TABEL 3

**Zeer sterk dynamisch**. In de rivieren en de getijdenwateren kan het substraat tijdens grote afvoeren van de grote rivieren en/of door sterke getijdestromingen sterk van vorm veranderen door de vorming van banken en geulen. Het substraat is daarbij tot op een diepte varierend van enkele decimeters tot enkele meters regelmatig tot continu in beweging. Ondanks deze dynamiek op korte tijdschaal, kunnen netto veranderingen over een langere periode gering zijn. Zo speelt er bijvoorbeeld in het getijdengebied vaak een zekere cycliciteit in erosie en sedimentatie; 's winters overheerst erosie en 's zomers sedimentatie. Voor de rivieren en de getijdenwateren geldt dat de stroomsnelheden boven 1 m/s liggen. In meren en kanalen komen ecotopen met deze zeer sterke dynamiek niet voor. Indien de bodem niet kunstmatig verhard is bestaat het substraat onder deze omstandigheden vrijwel altijd uit zandig materiaal (korrelgrootte \> 63 pm) of schelpen. Vestiging van vegetatie is niet mogelijk en de bodemfauna is arm en bestaat vooral uit een klein aantal beweeglijke epibenthische soorten.

**Sterk dynamisc**h. Milieu waarin het substraat tot op een diepte varierend van enkele centimeters tot decimeters regelmatig in beweging is. Vestiging van vegetatie wordt verhinderd ofwel er worden telkens nieuwe standplaatsen gevormd, wat specifieke aanpassing van soorten vergt. De bodemfauna wordt getypeerd door weinig wormen en relatief veel kreeftachtigen. Voor rivieren en getijdenwateren liggen stroomsnelheden beneden 1 m/s. De grens met 'dynamisch' ligt ongeveer bij 0,35 - 0,5 m/s. Voor meren en kanalen wordt het sterk dynamisch milieu bepaald door golven. Dit kan een gevolg zijn van wind in grotere systemen en aan de wind geexponeerde oever en van scheepvaart in kanalen. Het sediment is overwegend zand, bestaat uit schelpen of is kunstmatig verhard.

**Dynamisch**. Voor de rivieren geldt dat er bij hoogwater een duidelijk waar-neembare hoeveelheid sediment wordt afgezet van enkele millimeters tot centimeters dik, die zo groot is dat de bodemontwikkeling daardoor bei'nvloed wordt. Voor de getijdenwateren geldt dat bij gemiddeld hoogwater een duidelijk waarneembare hoeveelheid sediment sedimenteert en/of erodeert. In de zoete delen wordt veelal slibrijk materiaal afgezet, in de brakke delen vooral zand. De dikte van de (slib) laag varieert van enkele millimeters tot centimeters dik en is zo groot dat daardoor de bodemontwikkeling beTnvloed wordt. De bodem is in beweging, doch niet zodanig dat veel soortgroepen afwezig zijn. Zowel biomassa als diversiteit is bij deze dynamiek veelal maximaal. Stroomsnelheden in rivieren en in getijdenwateren liggen beneden 0,5 - 0,35 m/s. Voor de meren geldt dat van tijd tot tijd sedimentatie, transport of erosie optreedt, waardoor de bodemontwikkeling weliswaar wordt bei'nvloed, maar waardoor de vestiging of het voorkomen van vegetatie en bodemfauna niet blijvend worden verhinderd. Voor de kanalen geldt hetzelfde als bij de meren, maar langs de kanaaloevers treedt geen sedimentatie op.

**Laag dynamisch**. De bodem komt niet of nauwelijks in beweging ten gevolge van stroming of golven. Stroomsnelheden liggen beneden die beschreven voor dynamische milieus. In systemen met weinig gesuspendeerd slib geldt dat er zo weinig materiaal bezinkt (enkele millimeters), dat het nauwelijks meer waarneembaar is. Hierdoor blijft de bodem relatief slibarm en lijkt het op de dynamische situatie. Bij voldoende slibaanbod is er sprake van slibrijke, zachte bodems. Dit kan de zuurstofhuishouding beinvloeden en daarmee de vestiging van vegetatie en bodemfauna. Het laag dynamisch milieu komt ook voor achter vooroeververdedigingen. Deze verdedigingswerken komen veelvuldig voor bij kanalen en in toenemende mate ook in andere watersystemen. De bijbehorende ecotopen zijn daarom bij de kanalen wel beschreven, maar zullen voor de andere watersystemen worden beschreven in het rapport waarin de oeverzones nader worden belicht (Lorenz, in voorbereiding). Uit de beschrijving van de genoemde klassen blijkt al dat het resultaat van dit krachtenspel zich onder meer uit in verschillen in waterdiepte en bodemtype, die ook als indelingskenmerken fungeren (paragraaf 3.5 en 3.6).

## Waterdiepte {#sec-waterdiepte}

De waterdiepte is van invloed op het voorkomen van verschillende biologische soortgroepen. Klassen worden onderscheiden op basis van ecologische criteria of door abiotische factoren die direct bepalend zijn voor de aanwezigheid van biota (tabel 4). Er worden aldus vier klassen onderscheiden, maar daarbij is er vanuit gegaan dat de klassegrenzen binnen een watersysteem niet gelijk hoeven te zijn (tabel 5, figuur 6). De grens tussen ondiep en droog is overgenomen uit het RES, MES, BES en KES om aansluiting met deze systemen te waarborgen. Op enkele andere punten wijkt de indeling af van eerdere stelsels.

TABEL 4

Doordat systemen verschillen, verschillen ook de dieptegrenzen voor een bepaalde klasse tussen de watersystemen. Daarenboven zijn de grenzen ook vrij arbitrair. Zo is een dieptegrens bijvoorbeeld vaak gerelateerd aan de hoeveelheid licht die nog aanwezig is. Dit wordt bei'nvloed door de dynamiek, het bodemtype en de fytoplanktondichtheid als gevolg van de voedselrijkdom. De gekozen grenzen geven echter wel een goede indicatie van de verschillende zones in het oppervlaktewater. In zeer diep water kan als gevolg van stratificatie (zomerstratificatie, of per-manente stratificatie als gevolg van een diepe zouttong) langdurig zuurstofloosheid optreden, waardoor de omgeving onaantrekkelijk wordt voor een groot aantal groepen. Als gevolg van lichtgebrek vindt er op grote diepte ook geen primaire productie plaats. Daardoor is er relatief weinig voedsel aanwezig en is dat voedsel moeilijk bereikbaar voor duikeenden en visetende vogels. De diepte waarbij dit optreedt hangt af van het watertype. In stagnante wateren ligt de spronglaag vaak al op een diepte rond 5 meter. Niettemin zijn in het Usselmeer juist de delen dieper dan 5 meter in de wintermaanden de meest aantrekkelijke voedselgebieden voor visetende vogels als futen en zaagbekken (van Eerden & bij de Vaate, 1984; Platteeuw, 1985). Wellicht houdt zich dan juist meer vis op in het diepere water vanwege gunstiger watertemperaturen. In voorjaar en zomer vormen ook randen van diepere geulen of putten gunstige foerageerplekken voor visetende vogels (Voslamber ef al., 1995; Stam, 1995). In meer gemengde systemen ligt de bovengrens van zeer diep water dieper. Bij kanalen wordt 10 meter aangehouden. Niet ver van sluizen kan in putten in de getijdenwateren en in sommige kanalen stratificatie optreden als gevolg van een diepe zouttong. Aangenomen is dat dit ook vanaf 10 meter optreedt. In andere diepe, stromende delen van de getijdenwateren komt soms ook helemaal geen stratificatie voor en moet het gebied tot de klasse diep water worden gerekend. Diep water wordt onderscheiden op basis van het niet voorkomen van langdurige stratificatie in combinatie met de afwezigheid van een uitgebreide bedekking met vegetatie. In rivieren en kanalen begint deze klasse vanaf ongeveer 2 meter en in getijdenwateren en stagnante wateren als gevolg van een geringere opwerveling vanaf ongeveer 3 meter. Als gevolg van de eigenschap drijfvermogen kunnen bepaalde fytoplanktonsoorten succesvol concurreren om lichtenergie. In stagnante wateren wint de blauwwier Microcystis het daarom veelal van Planktothrix bij dieptes van meer dan ongeveer 3 meter. Bovendien heeft Microcystis veelal de hoogste toename van de groeisnelheid met de temperatuur, waardoor ze optimaal kunnen profiteren van een temperatuursprong als gevolg van micro-stratificatie. Dit is het optreden van verschillende waterlagen overdag, dat's nachts vaak weer teniet gedaan wordt en op enkele meters diepte plaats kan vinden. In deze zone kunnen duikeenden efficient foerageren op aanwezige driehoeksmosselen (de Leeuw, 1997). Vervolgens wordt matig diep water begrensd door de diepte tot waarop vegetatie nog uitgebreid kan voorkomen. Uiteraard is ook deze diepte afhankelijk van de hoeveelheid licht die de bodem kan bereiken en daarmee van de dynamiek, het bodemtype en de fytoplanktondichtheid als gevolg van de nutrientenrijkdom. Als gevolg van menging zal het aanwezige fytoplankton vaak veelvuldig aan licht worden blootgesteld en wordt concurrentie om voedingsstoffen belangrijker. De blauwwier Microcystis verliest het in stagnante wateren daarom vaak van Planktothrix, maar er komen ook veel andere groepen voor. In getijdenwateren is de zone van belang voor getijden-migreerders en komt hier bij uitstek de 'kinderkamerfunctie' tot uiting. De Jong (1999) geeft aan dat deze zone zich uitstrekt tot de geulrand, die in kustwateren rond 4 - 5 meter beneden NAP wordt gevonden. In ondiep water van grotere systemen is vegetatie weer vaak afwezig als gevolg van de mechanische krachten van met name golfwerking. Waterplanten komen hierdoor op dieptes van minder dan 0,50 meter nauwelijks voor (Remmelzwaal etal., 1998). Ook driehoeksmosselen worden slechts in marginale dichtheden aangetroffen in ondiep water. Dit hangt wellicht samen met een te hoge mate van golfdynamiek die aanhechting aan het substraat bemoeilijkt of met een te sterke gevoeligheid voor predatie door watervogels op een dergelijk geringe diepte. In geval van scheepvaart spelen twee factoren een rol: zuiging en golfslag. Op de Waal leidt een passage van duwvaart tot een waterstandsverlaging van ongeveer 0,4 meter. De invloed van de zuiging werkt echter dieper door. Bij de genoemde begrenzing van 1 meter bij gemiddeld laagwater is tevens de invloed van de golven al meegenomen. In dit dynamische milieu komen alleen enkele storingstolerante soorten voor. In stagnante wateren ontbreekt de golfdynamiek in veel gevallen of is minder groot. De ondiepe zone is hier dan ook aantrekkelijker voor biota, zoals grondeleenden en andere niet of weinig duikende watervogels. Zo foerageren kleine zwanen op de worteldelen van fonteinkruiden en knobbelzwanen en meerkoeten op kranswieren. De ondiepe delen van een watersysteem nemen een aparte plaats in door de potentiele aanwezigheid van uitgebreide oevervegetatie (helofyten), vaak in de vorm van velden van riet, biezen en/of lisdodde. De maximale diepte waarop deze zones voorkomen ligt veelal beneden 1 meter (Coops etal., 1999). Maas (1998) begrenst het ondiep water weliswaar bij 1,5 meter, maar geeft wel aan dat in de beddingbodem wortelende soorten als gele lis en drijvend fonteinkruid zich slechts vestigen in relatief rustige. circa 1 meter diepe delen. De oevervegetatie kan een belangrijke rol spelen als paai- en opgroeigebied voor vissen, maar vormt ook het leefgebied voor een breed scala aan moerasgebonden vogels (zoals rietzangvogels) en enkele karakteristieke soorten zoogdieren (bijvoorbeeld de otter) en amfibieen en reptielen (kikkers en de ringslang). Omdat als minimale diepte van de zone 'ondiep' 0,3 meter is aangehouden, is deze zone niet of nauwelijks geschikt voor wadende vogelsoorten als lepelaar en reigerachtigen.

## Bodemtype {#sec-bodemtype}

Het bodemtype is mede bepalend voor het voorkomen van diverse biologische groepen, zoals macrofauna en vegetatie. Vaak is echter niet geheel duidelijk welke eigenschappen hierbij een rol spelen; sediment met een hoog slib-gehalte is vaak ook rijk aan organisch materiaal en water, terwijl zuurstofgehalte en pH relatief laag zijn. Op bodems met een mobiele sliblaag is het aantal soorten macrofauna lager en zijn de meeste hoofdgroepen macro-fauna minder talrijk dan op zandbodems (Ligtvoet & Grimm, 1993; Noordhuis, 1997). In de randmeren verschuift de verhouding tussen muggenlarven en oligochaeten in de richting van de laatste naarmate het substraat slibrijker wordt (Noordhuis, 1997). Driehoeksmosselen hebben een voorkeur voor zandbodems, maar komen ook voor op kleibodems, mits daar harde elementen in het substraat (stenen of schelpen) aanwezig zijn. Van den Berg ef al. (1999) en Coops etal. (1999) vonden significante verbanden tussen het bodemtype uitgedrukt in het lutumgehalte en het voorkomen van een aantal soorten waterplanten. Een dikke sliblaag is in sterke mate beperkend voor waterplanten als gevolg van een gebrek aan stevigheid (moeilijk bewortel-baar) en zuurstof. De aanwezigheid van een bepaald type vegetatie of structurerende macrofaunasoorten als de driehoeksmossel is vervolgens weer veelal bepalend voor het voorkomen van specifieke macrofauna, vissen en vogels (Noordhuis, 1997). Het bodemtype wordt bepaald door de dynamiek en/of door het type ondergrond dat ter plaatse aanwezig is of daar is neergelegd. In erosiegebieden kan het grovere materiaal (grind of zand) aanwezig zijn of kunnen bodemlagen worden aangesneden die niet behoren bij de heersende dynamiek. Daar waar sedimentatie overheerst, kunnen afhankelijk van de dynamiek en de sedimentvracht afzettingen ontstaan van grind, zand, klei of slib. Ten Brinke (1997) illustreert voor het rivierengebied dat het bodemtype in de tijd kan wijzigen. Klei is vaak een afzetting gerelateerd aan een wat langere tijdschaal. Oudere mariene afzettingen vormen nu nog deels de ondergrond van de afgesloten zeearmen. Bij kanalen speelt toeval een rol in het bodemtype, daar deze wordt bepaald door de plaats waar het kanaal gegraven is. Veenbodems spelen geen rol van betekenis voor de permanent natte delen van de rijkswateren. In bijvoorbeeld het Usselmeer en de Biesbosch komen verspreid liggend wel kleine restanten veen aan de oppervlak. Tabel 6 geeft een algemene indeling van sedimenttypen. Naast de deeltjes-grootte onderscheidt slib zich van klei, doordat het ongeconsolideerd is. Slib neemt een bijzondere plaats in, door de relatief grote (re)activiteit. Een praktisch permanente aanwezigheid van gesuspendeerd slib (veel slib in combinatie met een grote dynamiek) zorgt voor een verlaging van het doorzicht waardoor zowel fytoplankton als hogere waterplanten in hun groei geremd worden of afwezig zijn. Ook kan zwevend slib remmend zijn voor de mate waarin zooplankton in staat is fytoplankton efficient te begra-zen (bijvoorbeeld Vermij ef al., 1992). De kwaliteit van slib is gevoelig voor de milieudruk en heeft een grote invloed op het al dan niet voorkomen van flora en fauna. De relevantie van onderscheid tussen de fractie klei en slib wordt momenteel nader bestudeerd (van de Laar & Menke, 1999).

TABEL 6

Bovengenoemde indeling in fracties sluit goed aan bij bodemkarteringen, maar minder bij ecologische vereisten van soorten. Dan speelt bijvoorbeeld het organisch stofgehalte een rol of het percentage slib van zandbodems. Voor een zandbodem stelt van der Meulen (1997) bijvoorbeeld dat het organisch stofgehalte kleiner moet zijn dan 22,5%, terwijl de Jong (1999) uitgaat van een slibgehalte lager dan 10%. In de praktijk zijn er vele gemengde bodems met overgangen tussen van slibarm naar slibrijk en van venig naar mineraal. Vooralsnog worden op basis van de mediane koirelgrootte de bodemtypen klei, slib, zand en verhard onderscheiden. Hard substraat wordt wel vaak door een duidelijk andere levensgemeenschap aan soorten gekenmerkt. Dit bodemtype bevat naast grindbanken ook schelpen-banken en materiaal dat veelal ter beveiliging of fixatie is aangebracht (bijvoorbeeld breuksteen, beton of asfalt). In het getijdengebied kan er verder sprake zijn van een geconsolideerde laag van veen of klei.

Het aanwezige bodemtype zal in een aantal gevallen niet of nauwelijks bepalend zijn voor de aanwezigheid van biologische soorten, daar een andere factor overheerst. Om deze reden wordt vooralsnog veelal geen onderscheid gemaakt op bodemtype wanneer systemen (zeer) sterk dynamisch zijn of dieper dan 5 meter. Er is onvoldoende ruimte geweest om voor de getijdenwateren onderscheid te maken tussen zand, klei en slib.

## Aanwezigheid van biologische soort(groep)  {#sec-aanwezigheid-van-biologische-soort(groep-}

In enkele gevallen worden binnen een ecotoop een of meerdere eco-elementen onderscheiden (zie paragraaf 2.2). Dit gebeurt op basis van de aanwezigheid van specifieke soort(groep)en. Het voorkomen van de soort(groep)en is afhankelijk van de abiotische randvoorwaarden, zoals genoemd in de voorgaande paragrafen. Daarnaast spelen onder meer successiestadium, predatie, voedselrijkdom, helderheid in relatie tot de waterdiepte en water-verversing een rol. Een aantal van deze operationele factoren heeft een duidelijke relatie met milieudruk als gevolg van de gebruiksdynamiek, zoals genoemd in paragraaf 2.5. Bij de keuze van de soorten is aangesloten op de monitoring, dat wil zeggen dat ze goed en eenvoudig zichtbaar dienen te zijn voor het gehele gebied en een groot deel van het jaar. Dit criterium valt vaak samen met het gegeven dat de betreffende groep structurerend is voor het gebied en dus bepalend voor het voorkomen van diverse andere soorten. In de praktijk gaat het hierbij veelal om vegetatie of het geclusterd voorkomen van schelpdieren. Bij de meren is de vegetatie onderscheiden in kranswieren, fonteinkruiden, Nymphaeiden en helofyten. In brakke delen van de getijdenwateren bestaat de vegetatie voornamelijk uit zeegras of wieren. De schelpdieren bestaan in de zoete wateren vooral uit driehoeksmosselen (Schloesser etal., 1994); in de brakke getijdenwateren kunnen andere schelpdieren een vergelijkbare rol spelen. Ook wordt hier een eco-element (overig) benthos onderscheiden. Verdere differentiatie is niet haalbaar vanuit het criterium van de karteerbaarheid en vaak niet zinvol met betrekking tot de ecologische relevantie. De volgende kwantitatieve maten worden aangehouden ten aanzien van het onderscheiden van eco-elementen.

-   Onder het eco-element fonteinkruiden vallen de submerse hogere plan-ten met een bedekking van \> 5% of een areaal pollen van meer \> 5% (Dudok van Heel ef al., 1992a).

-   In het eco-element kranswieren komen een of meerdere soorten van deze groep (Kranswieren-klasse Chareta fragilis; Schaminee ef al., 1995) voor in een aaneengesloten bedekking van \> 15%. Het percentage is afgeleid van dat voor fonteinkruiden, rekening houdend met het gegeven dat fonteinkruiden in tegenstelling tot kranswieren vaak de gehele waterkolom vullen.

-   Het eco-element Nymphaeiden (Waterlelie-verbond Nymphaeion; Schaminee ef al., 1995) bestaat uit een aaneengesloten bedekking van \> 5%. Nymphaeiden bestaan uit drijvende waterplanten, zoals de watergentiaan, gele plomp en waterlelies. Krabbenscheer is ook een drijvende plant, maar vormt geen afzonderlijk eco-element.

-   Bij de rivieren, getijdenwateren en kanalen komen waterplanten minder duidelijk voor in afzonderlijke gemeenschappen of was onvoldoende informatie beschikbaar om een onderverdeling te maken en daarom worden deze ook niet onderscheiden. Het gaat in brakke getijdenwateren echter veelal om macrowieren, zoals darmwier. In navolging van de RWES aquatisch maat voor kranswieren wordt voor een ondergrens van 15% bedekking aangehouden.

-   Helofyten worden als eco-element onderscheiden bij een aaneengesloten bedekking \> 5% of een areaal pollen \> 5%. Een strook helofyten krijgt pas ecologische betekenis bij een breedte van meer dan 0,5 meter.

-   De minimumgrens waarop driehoeksmosselen een eco-element vormen is gesteld op 500 g versgewicht per m2 (Jans etal., 2000). Andere tweekleppigen (bijvoorbeeld zwanenmossel) komen in het algemeen in zoete wateren niet in zulke dichtheden en oppervlakten voor, dat ze als basis voor een eco-element kunnen worden genomen.

-   Voor schelpdieren en andere benthos in de brakke getijdenwateren wordt voorlopig dezelfde grens aangehouden als voor driehoeksmosselen.

## 

TERRESTRISCH

## Hydrologie {#sec-hydrologie}

Dit kenmerk beschrijft de invloed van water op de drogere delen van watersystemen. Deze invloed is opgesplitst in de overstromingsduur voor dynamische systemen en het waterpeil voor stagnante systemen. In de terrestrische zone is de invloed en de beschikbaarheid van water van groot belang. Deze factor wordt dan ook vaak als dominant aangemerkt voor de structuur en soortensamenstelling langs watersystemen (CUR, 1999, Klijn et al., 1998, Coops, 1996, Van den Brink, 1990, De Graaf et al., 1990, Maenen, 1989, Leemans, 1989, Adriaanse, 1986). Voor nagenoeg alle watersystemen bestaat de terrestrische zone uit slechts 1 hydrologische klasse: overstromingsvrij. De echte, directe invloed van het watersysteem is minder groot dan in het water of in de oeverzone. In het getijdengebied is dit de zone boven extreem hoogwater (EHW); langs de meren en de kanalen wordt dit ook de droge terrestrische zone genoemd. Voor het rivierengebied worden twee hydrologische klassen onderscheiden, aangezien hier de oeverwalzone en de hogere uiterwaard tot het toepassingsbereik van RWES-terrestrisch gerekend worden (tabel 2). Deze zones kunnen periodiek overstromen en kennen als zodanig een grotere invloed van het water(systeem) op de ontwikkeling van flora en fauna. Naast een directe beïnvloeding is er sprake van een indirecte beïnvloeding door een hogere mechanische dynamiek als gevolg van overspoeling (zand- en slibsedimentatie of erosie). Onderscheid tussen deze twee landschappelijke zones in het rivierengebied wordt gemaakt op grond van de mechanische dynamiek (zie paragraaf @sec-mechanische-dynamiek). De klassenindeling voor de factor hydrologie komt overeen met de relevante klassen uit het RES voor de oeverwalzone en hogere uiterwaard.

TABEL?

## Gebruik/beheer {#sec-gebruikbeheer}

Dit kenmerk omvat alle bewuste en doelgerichte inrichtings- en beheersinvloeden die de mens uitoefent op de ontwikkeling van de bodem en de levensgemeenschap. Gebruik en beheer hebben een sterk effect op de structuur en soortensamenstelling, omdat door maaien of begrazing de diversiteit, biomassa en structuur van de vegetatie gestuurd wordt. Door het inzetten van grote grazers zal er een grotere diversiteit ontstaan in vegetatie: de ruigtekruiden zullen meer kans krijgen en het bos zal teruggedrongen worden. Door de inzet van intensief maai- of begrazingsbeheer verandert de vegetatie van ruigtekruiden of bos naar grasland. De gebruikte klassenindeling (tabel 4) stoelt op de mate van menselijke invloed.

| Klassen                    | Code | Beschrijving                                                                                                                                                                                                                                                                                                     |
|--------------------|-------|---------------------------------------------|
| Intensief beheer           | I    | Sterke invloed op de ontwikkeling van het substraat, vegetatie en fauna. Deze invloed is gericht op de ontwikkeling en het behoud van bepaalde natuurwaarden (b.v. hooiland) of op de productie van planten en dieren voor een (economisch) gebruiksdoel, zoals productiebossen en -graslanden.                  |
| Extensief beheer           | E    | Matige tot intensieve invloed op de ontwikkeling van het substraat, vegetatie en fauna gericht op de ontwikkeling en het behoud van bepaalde natuurwaarden. Hieronder valt begrazing door grote grazers en een beheer van extensief maaien en afvoeren, waardoor de soortendiversiteit van een ecotoop toeneemt. |
| Nauwelijks tot geen beheer | N    | Nauwelijks menselijke invloed, waardoor de ontwikkeling van flora en fauna op de standplaats wordt bepaald door natuurlijke processen.                                                                                                                                                                           |
| Kunstmatig hard substraat  | K    | Specifieke vorm van intensief beheer, waartoe de bebouwde en verharde terreinen behoren.                                                                                                                                                                                                                         |

\*Wat betreft beheer ter behoud van een natuurwaarde wordt het verschil tussen intensief en extensief beheer bepaald door de mate waarin het systeem door de mens gestuurd wordt. Voor het in stand houden van bestaande graslanden is extensieve beweiding voldoende (CUR, 1999). Daarom kunnen bij graslanden zowel de klassen extensief als intensief beheer gelden.

In Bal et al. (1995) worden met betrekking tot ‘natuurdoeltypen’ de klassen ‘’nagenoeg-natuurlijk’’, ‘’begeleid-natuurlijk’’, ‘’half-natuurlijk’’ en ‘’multifunctioneel gebruik’’ gehanteerd om de mate van menselijke invloed te beschrijven. Hoewel de indeling duidelijk afwijkend is, zijn er op basis van het type beheer overeenkomsten aan te geven tussen: - “Nauwelijks tot geen beheer” versus “nagenoeg natuurlijk” en “begeleid-natuurlijk”; - “Extensief beheer” versus “half-natuurlijk”; - “Intensief beheer” en “kunstmatig hard substraat” versus “multifunctioneel gebruik”.
